// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package user_pool

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cognitoidentityprovider-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.UserPool{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeUserPoolOutput
	resp, err = rm.sdkapi.DescribeUserPool(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeUserPool", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.UserPool.AccountRecoverySetting != nil {
		f0 := &svcapitypes.AccountRecoverySettingType{}
		if resp.UserPool.AccountRecoverySetting.RecoveryMechanisms != nil {
			f0f0 := []*svcapitypes.RecoveryOptionType{}
			for _, f0f0iter := range resp.UserPool.AccountRecoverySetting.RecoveryMechanisms {
				f0f0elem := &svcapitypes.RecoveryOptionType{}
				if f0f0iter.Name != "" {
					f0f0elem.Name = aws.String(string(f0f0iter.Name))
				}
				if f0f0iter.Priority != nil {
					priorityCopy := int64(*f0f0iter.Priority)
					f0f0elem.Priority = &priorityCopy
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.RecoveryMechanisms = f0f0
		}
		ko.Spec.AccountRecoverySetting = f0
	} else {
		ko.Spec.AccountRecoverySetting = nil
	}
	if resp.UserPool.AdminCreateUserConfig != nil {
		f1 := &svcapitypes.AdminCreateUserConfigType{}
		f1.AllowAdminCreateUserOnly = &resp.UserPool.AdminCreateUserConfig.AllowAdminCreateUserOnly
		if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate != nil {
			f1f1 := &svcapitypes.MessageTemplateType{}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage != nil {
				f1f1.EmailMessage = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage
			}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject != nil {
				f1f1.EmailSubject = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject
			}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage != nil {
				f1f1.SMSMessage = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage
			}
			f1.InviteMessageTemplate = f1f1
		}
		unusedAccountValidityDaysCopy := int64(resp.UserPool.AdminCreateUserConfig.UnusedAccountValidityDays)
		f1.UnusedAccountValidityDays = &unusedAccountValidityDaysCopy
		ko.Spec.AdminCreateUserConfig = f1
	} else {
		ko.Spec.AdminCreateUserConfig = nil
	}
	if resp.UserPool.AliasAttributes != nil {
		f2 := []*string{}
		for _, f2iter := range resp.UserPool.AliasAttributes {
			var f2elem *string
			f2elem = aws.String(string(f2iter))
			f2 = append(f2, f2elem)
		}
		ko.Spec.AliasAttributes = f2
	} else {
		ko.Spec.AliasAttributes = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.UserPool.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.UserPool.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.UserPool.AutoVerifiedAttributes != nil {
		f4 := []*string{}
		for _, f4iter := range resp.UserPool.AutoVerifiedAttributes {
			var f4elem *string
			f4elem = aws.String(string(f4iter))
			f4 = append(f4, f4elem)
		}
		ko.Spec.AutoVerifiedAttributes = f4
	} else {
		ko.Spec.AutoVerifiedAttributes = nil
	}
	if resp.UserPool.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.UserPool.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.UserPool.CustomDomain != nil {
		ko.Status.CustomDomain = resp.UserPool.CustomDomain
	} else {
		ko.Status.CustomDomain = nil
	}
	if resp.UserPool.DeletionProtection != "" {
		ko.Spec.DeletionProtection = aws.String(string(resp.UserPool.DeletionProtection))
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.UserPool.DeviceConfiguration != nil {
		f8 := &svcapitypes.DeviceConfigurationType{}
		f8.ChallengeRequiredOnNewDevice = &resp.UserPool.DeviceConfiguration.ChallengeRequiredOnNewDevice
		f8.DeviceOnlyRememberedOnUserPrompt = &resp.UserPool.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt
		ko.Spec.DeviceConfiguration = f8
	} else {
		ko.Spec.DeviceConfiguration = nil
	}
	if resp.UserPool.Domain != nil {
		ko.Status.Domain = resp.UserPool.Domain
	} else {
		ko.Status.Domain = nil
	}
	if resp.UserPool.EmailConfiguration != nil {
		f10 := &svcapitypes.EmailConfigurationType{}
		if resp.UserPool.EmailConfiguration.ConfigurationSet != nil {
			f10.ConfigurationSet = resp.UserPool.EmailConfiguration.ConfigurationSet
		}
		if resp.UserPool.EmailConfiguration.EmailSendingAccount != "" {
			f10.EmailSendingAccount = aws.String(string(resp.UserPool.EmailConfiguration.EmailSendingAccount))
		}
		if resp.UserPool.EmailConfiguration.From != nil {
			f10.From = resp.UserPool.EmailConfiguration.From
		}
		if resp.UserPool.EmailConfiguration.ReplyToEmailAddress != nil {
			f10.ReplyToEmailAddress = resp.UserPool.EmailConfiguration.ReplyToEmailAddress
		}
		if resp.UserPool.EmailConfiguration.SourceArn != nil {
			f10.SourceARN = resp.UserPool.EmailConfiguration.SourceArn
		}
		ko.Spec.EmailConfiguration = f10
	} else {
		ko.Spec.EmailConfiguration = nil
	}
	if resp.UserPool.EmailConfigurationFailure != nil {
		ko.Status.EmailConfigurationFailure = resp.UserPool.EmailConfigurationFailure
	} else {
		ko.Status.EmailConfigurationFailure = nil
	}
	if resp.UserPool.EmailVerificationMessage != nil {
		ko.Spec.EmailVerificationMessage = resp.UserPool.EmailVerificationMessage
	} else {
		ko.Spec.EmailVerificationMessage = nil
	}
	if resp.UserPool.EmailVerificationSubject != nil {
		ko.Spec.EmailVerificationSubject = resp.UserPool.EmailVerificationSubject
	} else {
		ko.Spec.EmailVerificationSubject = nil
	}
	estimatedNumberOfUsersCopy := int64(resp.UserPool.EstimatedNumberOfUsers)
	ko.Status.EstimatedNumberOfUsers = &estimatedNumberOfUsersCopy
	if resp.UserPool.Id != nil {
		ko.Status.ID = resp.UserPool.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.UserPool.IssuerConfiguration != nil {
		f16 := &svcapitypes.IssuerConfigurationType{}
		if resp.UserPool.IssuerConfiguration.Type != "" {
			f16.Type = aws.String(string(resp.UserPool.IssuerConfiguration.Type))
		}
		ko.Spec.IssuerConfiguration = f16
	} else {
		ko.Spec.IssuerConfiguration = nil
	}
	if resp.UserPool.KeyConfiguration != nil {
		f17 := &svcapitypes.KeyConfigurationType{}
		if resp.UserPool.KeyConfiguration.KeyType != "" {
			f17.KeyType = aws.String(string(resp.UserPool.KeyConfiguration.KeyType))
		}
		if resp.UserPool.KeyConfiguration.KmsKeyArn != nil {
			f17.KMSKeyARN = resp.UserPool.KeyConfiguration.KmsKeyArn
		}
		ko.Spec.KeyConfiguration = f17
	} else {
		ko.Spec.KeyConfiguration = nil
	}
	if resp.UserPool.LambdaConfig != nil {
		f18 := &svcapitypes.LambdaConfigType{}
		if resp.UserPool.LambdaConfig.CreateAuthChallenge != nil {
			f18.CreateAuthChallenge = resp.UserPool.LambdaConfig.CreateAuthChallenge
		}
		if resp.UserPool.LambdaConfig.CustomEmailSender != nil {
			f18f1 := &svcapitypes.CustomEmailLambdaVersionConfigType{}
			if resp.UserPool.LambdaConfig.CustomEmailSender.LambdaArn != nil {
				f18f1.LambdaARN = resp.UserPool.LambdaConfig.CustomEmailSender.LambdaArn
			}
			if resp.UserPool.LambdaConfig.CustomEmailSender.LambdaVersion != "" {
				f18f1.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.CustomEmailSender.LambdaVersion))
			}
			f18.CustomEmailSender = f18f1
		}
		if resp.UserPool.LambdaConfig.CustomMessage != nil {
			f18.CustomMessage = resp.UserPool.LambdaConfig.CustomMessage
		}
		if resp.UserPool.LambdaConfig.CustomSMSSender != nil {
			f18f3 := &svcapitypes.CustomSMSLambdaVersionConfigType{}
			if resp.UserPool.LambdaConfig.CustomSMSSender.LambdaArn != nil {
				f18f3.LambdaARN = resp.UserPool.LambdaConfig.CustomSMSSender.LambdaArn
			}
			if resp.UserPool.LambdaConfig.CustomSMSSender.LambdaVersion != "" {
				f18f3.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.CustomSMSSender.LambdaVersion))
			}
			f18.CustomSMSSender = f18f3
		}
		if resp.UserPool.LambdaConfig.DefineAuthChallenge != nil {
			f18.DefineAuthChallenge = resp.UserPool.LambdaConfig.DefineAuthChallenge
		}
		if resp.UserPool.LambdaConfig.InboundFederation != nil {
			f18f5 := &svcapitypes.InboundFederationLambdaType{}
			if resp.UserPool.LambdaConfig.InboundFederation.LambdaArn != nil {
				f18f5.LambdaARN = resp.UserPool.LambdaConfig.InboundFederation.LambdaArn
			}
			if resp.UserPool.LambdaConfig.InboundFederation.LambdaVersion != "" {
				f18f5.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.InboundFederation.LambdaVersion))
			}
			f18.InboundFederation = f18f5
		}
		if resp.UserPool.LambdaConfig.KMSKeyID != nil {
			f18.KMSKeyID = resp.UserPool.LambdaConfig.KMSKeyID
		}
		if resp.UserPool.LambdaConfig.PostAuthentication != nil {
			f18.PostAuthentication = resp.UserPool.LambdaConfig.PostAuthentication
		}
		if resp.UserPool.LambdaConfig.PostConfirmation != nil {
			f18.PostConfirmation = resp.UserPool.LambdaConfig.PostConfirmation
		}
		if resp.UserPool.LambdaConfig.PreAuthentication != nil {
			f18.PreAuthentication = resp.UserPool.LambdaConfig.PreAuthentication
		}
		if resp.UserPool.LambdaConfig.PreSignUp != nil {
			f18.PreSignUp = resp.UserPool.LambdaConfig.PreSignUp
		}
		if resp.UserPool.LambdaConfig.PreTokenGeneration != nil {
			f18.PreTokenGeneration = resp.UserPool.LambdaConfig.PreTokenGeneration
		}
		if resp.UserPool.LambdaConfig.PreTokenGenerationConfig != nil {
			f18f12 := &svcapitypes.PreTokenGenerationVersionConfigType{}
			if resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaArn != nil {
				f18f12.LambdaARN = resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaArn
			}
			if resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaVersion != "" {
				f18f12.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaVersion))
			}
			f18.PreTokenGenerationConfig = f18f12
		}
		if resp.UserPool.LambdaConfig.UserMigration != nil {
			f18.UserMigration = resp.UserPool.LambdaConfig.UserMigration
		}
		if resp.UserPool.LambdaConfig.VerifyAuthChallengeResponse != nil {
			f18.VerifyAuthChallengeResponse = resp.UserPool.LambdaConfig.VerifyAuthChallengeResponse
		}
		ko.Spec.LambdaConfig = f18
	} else {
		ko.Spec.LambdaConfig = nil
	}
	if resp.UserPool.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = &metav1.Time{*resp.UserPool.LastModifiedDate}
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.UserPool.MfaConfiguration != "" {
		ko.Spec.MFAConfiguration = aws.String(string(resp.UserPool.MfaConfiguration))
	} else {
		ko.Spec.MFAConfiguration = nil
	}
	if resp.UserPool.Name != nil {
		ko.Spec.Name = resp.UserPool.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.UserPool.Policies != nil {
		f22 := &svcapitypes.UserPoolPolicyType{}
		if resp.UserPool.Policies.PasswordPolicy != nil {
			f22f0 := &svcapitypes.PasswordPolicyType{}
			if resp.UserPool.Policies.PasswordPolicy.MinimumLength != nil {
				minimumLengthCopy := int64(*resp.UserPool.Policies.PasswordPolicy.MinimumLength)
				f22f0.MinimumLength = &minimumLengthCopy
			}
			f22f0.RequireLowercase = &resp.UserPool.Policies.PasswordPolicy.RequireLowercase
			f22f0.RequireNumbers = &resp.UserPool.Policies.PasswordPolicy.RequireNumbers
			f22f0.RequireSymbols = &resp.UserPool.Policies.PasswordPolicy.RequireSymbols
			f22f0.RequireUppercase = &resp.UserPool.Policies.PasswordPolicy.RequireUppercase
			temporaryPasswordValidityDaysCopy := int64(resp.UserPool.Policies.PasswordPolicy.TemporaryPasswordValidityDays)
			f22f0.TemporaryPasswordValidityDays = &temporaryPasswordValidityDaysCopy
			f22.PasswordPolicy = f22f0
		}
		ko.Spec.Policies = f22
	} else {
		ko.Spec.Policies = nil
	}
	if resp.UserPool.SchemaAttributes != nil {
		f23 := []*svcapitypes.SchemaAttributeType{}
		for _, f23iter := range resp.UserPool.SchemaAttributes {
			f23elem := &svcapitypes.SchemaAttributeType{}
			if f23iter.AttributeDataType != "" {
				f23elem.AttributeDataType = aws.String(string(f23iter.AttributeDataType))
			}
			if f23iter.DeveloperOnlyAttribute != nil {
				f23elem.DeveloperOnlyAttribute = f23iter.DeveloperOnlyAttribute
			}
			if f23iter.Mutable != nil {
				f23elem.Mutable = f23iter.Mutable
			}
			if f23iter.Name != nil {
				f23elem.Name = f23iter.Name
			}
			if f23iter.NumberAttributeConstraints != nil {
				f23elemf4 := &svcapitypes.NumberAttributeConstraintsType{}
				if f23iter.NumberAttributeConstraints.MaxValue != nil {
					f23elemf4.MaxValue = f23iter.NumberAttributeConstraints.MaxValue
				}
				if f23iter.NumberAttributeConstraints.MinValue != nil {
					f23elemf4.MinValue = f23iter.NumberAttributeConstraints.MinValue
				}
				f23elem.NumberAttributeConstraints = f23elemf4
			}
			if f23iter.Required != nil {
				f23elem.Required = f23iter.Required
			}
			if f23iter.StringAttributeConstraints != nil {
				f23elemf6 := &svcapitypes.StringAttributeConstraintsType{}
				if f23iter.StringAttributeConstraints.MaxLength != nil {
					f23elemf6.MaxLength = f23iter.StringAttributeConstraints.MaxLength
				}
				if f23iter.StringAttributeConstraints.MinLength != nil {
					f23elemf6.MinLength = f23iter.StringAttributeConstraints.MinLength
				}
				f23elem.StringAttributeConstraints = f23elemf6
			}
			f23 = append(f23, f23elem)
		}
		ko.Status.SchemaAttributes = f23
	} else {
		ko.Status.SchemaAttributes = nil
	}
	if resp.UserPool.SmsAuthenticationMessage != nil {
		ko.Spec.SmsAuthenticationMessage = resp.UserPool.SmsAuthenticationMessage
	} else {
		ko.Spec.SmsAuthenticationMessage = nil
	}
	if resp.UserPool.SmsConfiguration != nil {
		f25 := &svcapitypes.SmsConfigurationType{}
		if resp.UserPool.SmsConfiguration.EumsSms != nil {
			f25f0 := &svcapitypes.EumsSmsConfigurationType{}
			if resp.UserPool.SmsConfiguration.EumsSms.CallerArn != nil {
				f25f0.CallerARN = resp.UserPool.SmsConfiguration.EumsSms.CallerArn
			}
			if resp.UserPool.SmsConfiguration.EumsSms.ConfigurationSetName != nil {
				f25f0.ConfigurationSetName = resp.UserPool.SmsConfiguration.EumsSms.ConfigurationSetName
			}
			if resp.UserPool.SmsConfiguration.EumsSms.ExternalId != nil {
				f25f0.ExternalID = resp.UserPool.SmsConfiguration.EumsSms.ExternalId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.InEntityId != nil {
				f25f0.InEntityID = resp.UserPool.SmsConfiguration.EumsSms.InEntityId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.InTemplateId != nil {
				f25f0.InTemplateID = resp.UserPool.SmsConfiguration.EumsSms.InTemplateId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.OriginationIdentity != nil {
				f25f0.OriginationIdentity = resp.UserPool.SmsConfiguration.EumsSms.OriginationIdentity
			}
			if resp.UserPool.SmsConfiguration.EumsSms.Region != nil {
				f25f0.Region = resp.UserPool.SmsConfiguration.EumsSms.Region
			}
			f25.EumsSms = f25f0
		}
		if resp.UserPool.SmsConfiguration.ExternalId != nil {
			f25.ExternalID = resp.UserPool.SmsConfiguration.ExternalId
		}
		if resp.UserPool.SmsConfiguration.SnsCallerArn != nil {
			f25.SNSCallerARN = resp.UserPool.SmsConfiguration.SnsCallerArn
		}
		if resp.UserPool.SmsConfiguration.SnsRegion != nil {
			f25.SNSRegion = resp.UserPool.SmsConfiguration.SnsRegion
		}
		ko.Spec.SmsConfiguration = f25
	} else {
		ko.Spec.SmsConfiguration = nil
	}
	if resp.UserPool.SmsConfigurationFailure != nil {
		ko.Status.SmsConfigurationFailure = resp.UserPool.SmsConfigurationFailure
	} else {
		ko.Status.SmsConfigurationFailure = nil
	}
	if resp.UserPool.SmsVerificationMessage != nil {
		ko.Spec.SmsVerificationMessage = resp.UserPool.SmsVerificationMessage
	} else {
		ko.Spec.SmsVerificationMessage = nil
	}
	if resp.UserPool.Status != "" {
		ko.Status.Status = aws.String(string(resp.UserPool.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.UserPool.UserAttributeUpdateSettings != nil {
		f29 := &svcapitypes.UserAttributeUpdateSettingsType{}
		if resp.UserPool.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate != nil {
			f29f0 := []*string{}
			for _, f29f0iter := range resp.UserPool.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate {
				var f29f0elem *string
				f29f0elem = aws.String(string(f29f0iter))
				f29f0 = append(f29f0, f29f0elem)
			}
			f29.AttributesRequireVerificationBeforeUpdate = f29f0
		}
		ko.Spec.UserAttributeUpdateSettings = f29
	} else {
		ko.Spec.UserAttributeUpdateSettings = nil
	}
	if resp.UserPool.UserPoolAddOns != nil {
		f30 := &svcapitypes.UserPoolAddOnsType{}
		if resp.UserPool.UserPoolAddOns.AdvancedSecurityMode != "" {
			f30.AdvancedSecurityMode = aws.String(string(resp.UserPool.UserPoolAddOns.AdvancedSecurityMode))
		}
		ko.Spec.UserPoolAddOns = f30
	} else {
		ko.Spec.UserPoolAddOns = nil
	}
	if resp.UserPool.UserPoolTags != nil {
		ko.Spec.UserPoolTags = aws.StringMap(resp.UserPool.UserPoolTags)
	} else {
		ko.Spec.UserPoolTags = nil
	}
	if resp.UserPool.UsernameAttributes != nil {
		f32 := []*string{}
		for _, f32iter := range resp.UserPool.UsernameAttributes {
			var f32elem *string
			f32elem = aws.String(string(f32iter))
			f32 = append(f32, f32elem)
		}
		ko.Spec.UsernameAttributes = f32
	} else {
		ko.Spec.UsernameAttributes = nil
	}
	if resp.UserPool.UsernameConfiguration != nil {
		f33 := &svcapitypes.UsernameConfigurationType{}
		if resp.UserPool.UsernameConfiguration.CaseSensitive != nil {
			f33.CaseSensitive = resp.UserPool.UsernameConfiguration.CaseSensitive
		}
		ko.Spec.UsernameConfiguration = f33
	} else {
		ko.Spec.UsernameConfiguration = nil
	}
	if resp.UserPool.VerificationMessageTemplate != nil {
		f34 := &svcapitypes.VerificationMessageTemplateType{}
		if resp.UserPool.VerificationMessageTemplate.DefaultEmailOption != "" {
			f34.DefaultEmailOption = aws.String(string(resp.UserPool.VerificationMessageTemplate.DefaultEmailOption))
		}
		if resp.UserPool.VerificationMessageTemplate.EmailMessage != nil {
			f34.EmailMessage = resp.UserPool.VerificationMessageTemplate.EmailMessage
		}
		if resp.UserPool.VerificationMessageTemplate.EmailMessageByLink != nil {
			f34.EmailMessageByLink = resp.UserPool.VerificationMessageTemplate.EmailMessageByLink
		}
		if resp.UserPool.VerificationMessageTemplate.EmailSubject != nil {
			f34.EmailSubject = resp.UserPool.VerificationMessageTemplate.EmailSubject
		}
		if resp.UserPool.VerificationMessageTemplate.EmailSubjectByLink != nil {
			f34.EmailSubjectByLink = resp.UserPool.VerificationMessageTemplate.EmailSubjectByLink
		}
		if resp.UserPool.VerificationMessageTemplate.SmsMessage != nil {
			f34.SmsMessage = resp.UserPool.VerificationMessageTemplate.SmsMessage
		}
		ko.Spec.VerificationMessageTemplate = f34
	} else {
		ko.Spec.VerificationMessageTemplate = nil
	}

	rm.setStatusDefaults(ko)
	output, err := rm.sdkapi.ListTagsForResource(
		ctx,
		&svcsdk.ListTagsForResourceInput{
			ResourceArn: (*string)(ko.Status.ACKResourceMetadata.ARN),
		},
	)
	rm.metrics.RecordAPICall("READ_MANY", "ListTagsForResource", err)
	if err != nil {
		return nil, err
	}

	ko.Spec.Tags = aws.StringMap(output.Tags)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeUserPoolInput, error) {
	res := &svcsdk.DescribeUserPoolInput{}

	if r.ko.Status.ID != nil {
		res.UserPoolId = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateUserPoolOutput
	_ = resp
	resp, err = rm.sdkapi.CreateUserPool(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateUserPool", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.UserPool.AccountRecoverySetting != nil {
		f0 := &svcapitypes.AccountRecoverySettingType{}
		if resp.UserPool.AccountRecoverySetting.RecoveryMechanisms != nil {
			f0f0 := []*svcapitypes.RecoveryOptionType{}
			for _, f0f0iter := range resp.UserPool.AccountRecoverySetting.RecoveryMechanisms {
				f0f0elem := &svcapitypes.RecoveryOptionType{}
				if f0f0iter.Name != "" {
					f0f0elem.Name = aws.String(string(f0f0iter.Name))
				}
				if f0f0iter.Priority != nil {
					priorityCopy := int64(*f0f0iter.Priority)
					f0f0elem.Priority = &priorityCopy
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.RecoveryMechanisms = f0f0
		}
		ko.Spec.AccountRecoverySetting = f0
	} else {
		ko.Spec.AccountRecoverySetting = nil
	}
	if resp.UserPool.AdminCreateUserConfig != nil {
		f1 := &svcapitypes.AdminCreateUserConfigType{}
		f1.AllowAdminCreateUserOnly = &resp.UserPool.AdminCreateUserConfig.AllowAdminCreateUserOnly
		if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate != nil {
			f1f1 := &svcapitypes.MessageTemplateType{}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage != nil {
				f1f1.EmailMessage = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage
			}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject != nil {
				f1f1.EmailSubject = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject
			}
			if resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage != nil {
				f1f1.SMSMessage = resp.UserPool.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage
			}
			f1.InviteMessageTemplate = f1f1
		}
		unusedAccountValidityDaysCopy := int64(resp.UserPool.AdminCreateUserConfig.UnusedAccountValidityDays)
		f1.UnusedAccountValidityDays = &unusedAccountValidityDaysCopy
		ko.Spec.AdminCreateUserConfig = f1
	} else {
		ko.Spec.AdminCreateUserConfig = nil
	}
	if resp.UserPool.AliasAttributes != nil {
		f2 := []*string{}
		for _, f2iter := range resp.UserPool.AliasAttributes {
			var f2elem *string
			f2elem = aws.String(string(f2iter))
			f2 = append(f2, f2elem)
		}
		ko.Spec.AliasAttributes = f2
	} else {
		ko.Spec.AliasAttributes = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.UserPool.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.UserPool.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.UserPool.AutoVerifiedAttributes != nil {
		f4 := []*string{}
		for _, f4iter := range resp.UserPool.AutoVerifiedAttributes {
			var f4elem *string
			f4elem = aws.String(string(f4iter))
			f4 = append(f4, f4elem)
		}
		ko.Spec.AutoVerifiedAttributes = f4
	} else {
		ko.Spec.AutoVerifiedAttributes = nil
	}
	if resp.UserPool.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.UserPool.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.UserPool.CustomDomain != nil {
		ko.Status.CustomDomain = resp.UserPool.CustomDomain
	} else {
		ko.Status.CustomDomain = nil
	}
	if resp.UserPool.DeletionProtection != "" {
		ko.Spec.DeletionProtection = aws.String(string(resp.UserPool.DeletionProtection))
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.UserPool.DeviceConfiguration != nil {
		f8 := &svcapitypes.DeviceConfigurationType{}
		f8.ChallengeRequiredOnNewDevice = &resp.UserPool.DeviceConfiguration.ChallengeRequiredOnNewDevice
		f8.DeviceOnlyRememberedOnUserPrompt = &resp.UserPool.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt
		ko.Spec.DeviceConfiguration = f8
	} else {
		ko.Spec.DeviceConfiguration = nil
	}
	if resp.UserPool.Domain != nil {
		ko.Status.Domain = resp.UserPool.Domain
	} else {
		ko.Status.Domain = nil
	}
	if resp.UserPool.EmailConfiguration != nil {
		f10 := &svcapitypes.EmailConfigurationType{}
		if resp.UserPool.EmailConfiguration.ConfigurationSet != nil {
			f10.ConfigurationSet = resp.UserPool.EmailConfiguration.ConfigurationSet
		}
		if resp.UserPool.EmailConfiguration.EmailSendingAccount != "" {
			f10.EmailSendingAccount = aws.String(string(resp.UserPool.EmailConfiguration.EmailSendingAccount))
		}
		if resp.UserPool.EmailConfiguration.From != nil {
			f10.From = resp.UserPool.EmailConfiguration.From
		}
		if resp.UserPool.EmailConfiguration.ReplyToEmailAddress != nil {
			f10.ReplyToEmailAddress = resp.UserPool.EmailConfiguration.ReplyToEmailAddress
		}
		if resp.UserPool.EmailConfiguration.SourceArn != nil {
			f10.SourceARN = resp.UserPool.EmailConfiguration.SourceArn
		}
		ko.Spec.EmailConfiguration = f10
	} else {
		ko.Spec.EmailConfiguration = nil
	}
	if resp.UserPool.EmailConfigurationFailure != nil {
		ko.Status.EmailConfigurationFailure = resp.UserPool.EmailConfigurationFailure
	} else {
		ko.Status.EmailConfigurationFailure = nil
	}
	if resp.UserPool.EmailVerificationMessage != nil {
		ko.Spec.EmailVerificationMessage = resp.UserPool.EmailVerificationMessage
	} else {
		ko.Spec.EmailVerificationMessage = nil
	}
	if resp.UserPool.EmailVerificationSubject != nil {
		ko.Spec.EmailVerificationSubject = resp.UserPool.EmailVerificationSubject
	} else {
		ko.Spec.EmailVerificationSubject = nil
	}
	estimatedNumberOfUsersCopy := int64(resp.UserPool.EstimatedNumberOfUsers)
	ko.Status.EstimatedNumberOfUsers = &estimatedNumberOfUsersCopy
	if resp.UserPool.Id != nil {
		ko.Status.ID = resp.UserPool.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.UserPool.IssuerConfiguration != nil {
		f16 := &svcapitypes.IssuerConfigurationType{}
		if resp.UserPool.IssuerConfiguration.Type != "" {
			f16.Type = aws.String(string(resp.UserPool.IssuerConfiguration.Type))
		}
		ko.Spec.IssuerConfiguration = f16
	} else {
		ko.Spec.IssuerConfiguration = nil
	}
	if resp.UserPool.KeyConfiguration != nil {
		f17 := &svcapitypes.KeyConfigurationType{}
		if resp.UserPool.KeyConfiguration.KeyType != "" {
			f17.KeyType = aws.String(string(resp.UserPool.KeyConfiguration.KeyType))
		}
		if resp.UserPool.KeyConfiguration.KmsKeyArn != nil {
			f17.KMSKeyARN = resp.UserPool.KeyConfiguration.KmsKeyArn
		}
		ko.Spec.KeyConfiguration = f17
	} else {
		ko.Spec.KeyConfiguration = nil
	}
	if resp.UserPool.LambdaConfig != nil {
		f18 := &svcapitypes.LambdaConfigType{}
		if resp.UserPool.LambdaConfig.CreateAuthChallenge != nil {
			f18.CreateAuthChallenge = resp.UserPool.LambdaConfig.CreateAuthChallenge
		}
		if resp.UserPool.LambdaConfig.CustomEmailSender != nil {
			f18f1 := &svcapitypes.CustomEmailLambdaVersionConfigType{}
			if resp.UserPool.LambdaConfig.CustomEmailSender.LambdaArn != nil {
				f18f1.LambdaARN = resp.UserPool.LambdaConfig.CustomEmailSender.LambdaArn
			}
			if resp.UserPool.LambdaConfig.CustomEmailSender.LambdaVersion != "" {
				f18f1.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.CustomEmailSender.LambdaVersion))
			}
			f18.CustomEmailSender = f18f1
		}
		if resp.UserPool.LambdaConfig.CustomMessage != nil {
			f18.CustomMessage = resp.UserPool.LambdaConfig.CustomMessage
		}
		if resp.UserPool.LambdaConfig.CustomSMSSender != nil {
			f18f3 := &svcapitypes.CustomSMSLambdaVersionConfigType{}
			if resp.UserPool.LambdaConfig.CustomSMSSender.LambdaArn != nil {
				f18f3.LambdaARN = resp.UserPool.LambdaConfig.CustomSMSSender.LambdaArn
			}
			if resp.UserPool.LambdaConfig.CustomSMSSender.LambdaVersion != "" {
				f18f3.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.CustomSMSSender.LambdaVersion))
			}
			f18.CustomSMSSender = f18f3
		}
		if resp.UserPool.LambdaConfig.DefineAuthChallenge != nil {
			f18.DefineAuthChallenge = resp.UserPool.LambdaConfig.DefineAuthChallenge
		}
		if resp.UserPool.LambdaConfig.InboundFederation != nil {
			f18f5 := &svcapitypes.InboundFederationLambdaType{}
			if resp.UserPool.LambdaConfig.InboundFederation.LambdaArn != nil {
				f18f5.LambdaARN = resp.UserPool.LambdaConfig.InboundFederation.LambdaArn
			}
			if resp.UserPool.LambdaConfig.InboundFederation.LambdaVersion != "" {
				f18f5.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.InboundFederation.LambdaVersion))
			}
			f18.InboundFederation = f18f5
		}
		if resp.UserPool.LambdaConfig.KMSKeyID != nil {
			f18.KMSKeyID = resp.UserPool.LambdaConfig.KMSKeyID
		}
		if resp.UserPool.LambdaConfig.PostAuthentication != nil {
			f18.PostAuthentication = resp.UserPool.LambdaConfig.PostAuthentication
		}
		if resp.UserPool.LambdaConfig.PostConfirmation != nil {
			f18.PostConfirmation = resp.UserPool.LambdaConfig.PostConfirmation
		}
		if resp.UserPool.LambdaConfig.PreAuthentication != nil {
			f18.PreAuthentication = resp.UserPool.LambdaConfig.PreAuthentication
		}
		if resp.UserPool.LambdaConfig.PreSignUp != nil {
			f18.PreSignUp = resp.UserPool.LambdaConfig.PreSignUp
		}
		if resp.UserPool.LambdaConfig.PreTokenGeneration != nil {
			f18.PreTokenGeneration = resp.UserPool.LambdaConfig.PreTokenGeneration
		}
		if resp.UserPool.LambdaConfig.PreTokenGenerationConfig != nil {
			f18f12 := &svcapitypes.PreTokenGenerationVersionConfigType{}
			if resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaArn != nil {
				f18f12.LambdaARN = resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaArn
			}
			if resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaVersion != "" {
				f18f12.LambdaVersion = aws.String(string(resp.UserPool.LambdaConfig.PreTokenGenerationConfig.LambdaVersion))
			}
			f18.PreTokenGenerationConfig = f18f12
		}
		if resp.UserPool.LambdaConfig.UserMigration != nil {
			f18.UserMigration = resp.UserPool.LambdaConfig.UserMigration
		}
		if resp.UserPool.LambdaConfig.VerifyAuthChallengeResponse != nil {
			f18.VerifyAuthChallengeResponse = resp.UserPool.LambdaConfig.VerifyAuthChallengeResponse
		}
		ko.Spec.LambdaConfig = f18
	} else {
		ko.Spec.LambdaConfig = nil
	}
	if resp.UserPool.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = &metav1.Time{*resp.UserPool.LastModifiedDate}
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.UserPool.MfaConfiguration != "" {
		ko.Spec.MFAConfiguration = aws.String(string(resp.UserPool.MfaConfiguration))
	} else {
		ko.Spec.MFAConfiguration = nil
	}
	if resp.UserPool.Name != nil {
		ko.Spec.Name = resp.UserPool.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.UserPool.Policies != nil {
		f22 := &svcapitypes.UserPoolPolicyType{}
		if resp.UserPool.Policies.PasswordPolicy != nil {
			f22f0 := &svcapitypes.PasswordPolicyType{}
			if resp.UserPool.Policies.PasswordPolicy.MinimumLength != nil {
				minimumLengthCopy := int64(*resp.UserPool.Policies.PasswordPolicy.MinimumLength)
				f22f0.MinimumLength = &minimumLengthCopy
			}
			f22f0.RequireLowercase = &resp.UserPool.Policies.PasswordPolicy.RequireLowercase
			f22f0.RequireNumbers = &resp.UserPool.Policies.PasswordPolicy.RequireNumbers
			f22f0.RequireSymbols = &resp.UserPool.Policies.PasswordPolicy.RequireSymbols
			f22f0.RequireUppercase = &resp.UserPool.Policies.PasswordPolicy.RequireUppercase
			temporaryPasswordValidityDaysCopy := int64(resp.UserPool.Policies.PasswordPolicy.TemporaryPasswordValidityDays)
			f22f0.TemporaryPasswordValidityDays = &temporaryPasswordValidityDaysCopy
			f22.PasswordPolicy = f22f0
		}
		ko.Spec.Policies = f22
	} else {
		ko.Spec.Policies = nil
	}
	if resp.UserPool.SchemaAttributes != nil {
		f23 := []*svcapitypes.SchemaAttributeType{}
		for _, f23iter := range resp.UserPool.SchemaAttributes {
			f23elem := &svcapitypes.SchemaAttributeType{}
			if f23iter.AttributeDataType != "" {
				f23elem.AttributeDataType = aws.String(string(f23iter.AttributeDataType))
			}
			if f23iter.DeveloperOnlyAttribute != nil {
				f23elem.DeveloperOnlyAttribute = f23iter.DeveloperOnlyAttribute
			}
			if f23iter.Mutable != nil {
				f23elem.Mutable = f23iter.Mutable
			}
			if f23iter.Name != nil {
				f23elem.Name = f23iter.Name
			}
			if f23iter.NumberAttributeConstraints != nil {
				f23elemf4 := &svcapitypes.NumberAttributeConstraintsType{}
				if f23iter.NumberAttributeConstraints.MaxValue != nil {
					f23elemf4.MaxValue = f23iter.NumberAttributeConstraints.MaxValue
				}
				if f23iter.NumberAttributeConstraints.MinValue != nil {
					f23elemf4.MinValue = f23iter.NumberAttributeConstraints.MinValue
				}
				f23elem.NumberAttributeConstraints = f23elemf4
			}
			if f23iter.Required != nil {
				f23elem.Required = f23iter.Required
			}
			if f23iter.StringAttributeConstraints != nil {
				f23elemf6 := &svcapitypes.StringAttributeConstraintsType{}
				if f23iter.StringAttributeConstraints.MaxLength != nil {
					f23elemf6.MaxLength = f23iter.StringAttributeConstraints.MaxLength
				}
				if f23iter.StringAttributeConstraints.MinLength != nil {
					f23elemf6.MinLength = f23iter.StringAttributeConstraints.MinLength
				}
				f23elem.StringAttributeConstraints = f23elemf6
			}
			f23 = append(f23, f23elem)
		}
		ko.Status.SchemaAttributes = f23
	} else {
		ko.Status.SchemaAttributes = nil
	}
	if resp.UserPool.SmsAuthenticationMessage != nil {
		ko.Spec.SmsAuthenticationMessage = resp.UserPool.SmsAuthenticationMessage
	} else {
		ko.Spec.SmsAuthenticationMessage = nil
	}
	if resp.UserPool.SmsConfiguration != nil {
		f25 := &svcapitypes.SmsConfigurationType{}
		if resp.UserPool.SmsConfiguration.EumsSms != nil {
			f25f0 := &svcapitypes.EumsSmsConfigurationType{}
			if resp.UserPool.SmsConfiguration.EumsSms.CallerArn != nil {
				f25f0.CallerARN = resp.UserPool.SmsConfiguration.EumsSms.CallerArn
			}
			if resp.UserPool.SmsConfiguration.EumsSms.ConfigurationSetName != nil {
				f25f0.ConfigurationSetName = resp.UserPool.SmsConfiguration.EumsSms.ConfigurationSetName
			}
			if resp.UserPool.SmsConfiguration.EumsSms.ExternalId != nil {
				f25f0.ExternalID = resp.UserPool.SmsConfiguration.EumsSms.ExternalId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.InEntityId != nil {
				f25f0.InEntityID = resp.UserPool.SmsConfiguration.EumsSms.InEntityId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.InTemplateId != nil {
				f25f0.InTemplateID = resp.UserPool.SmsConfiguration.EumsSms.InTemplateId
			}
			if resp.UserPool.SmsConfiguration.EumsSms.OriginationIdentity != nil {
				f25f0.OriginationIdentity = resp.UserPool.SmsConfiguration.EumsSms.OriginationIdentity
			}
			if resp.UserPool.SmsConfiguration.EumsSms.Region != nil {
				f25f0.Region = resp.UserPool.SmsConfiguration.EumsSms.Region
			}
			f25.EumsSms = f25f0
		}
		if resp.UserPool.SmsConfiguration.ExternalId != nil {
			f25.ExternalID = resp.UserPool.SmsConfiguration.ExternalId
		}
		if resp.UserPool.SmsConfiguration.SnsCallerArn != nil {
			f25.SNSCallerARN = resp.UserPool.SmsConfiguration.SnsCallerArn
		}
		if resp.UserPool.SmsConfiguration.SnsRegion != nil {
			f25.SNSRegion = resp.UserPool.SmsConfiguration.SnsRegion
		}
		ko.Spec.SmsConfiguration = f25
	} else {
		ko.Spec.SmsConfiguration = nil
	}
	if resp.UserPool.SmsConfigurationFailure != nil {
		ko.Status.SmsConfigurationFailure = resp.UserPool.SmsConfigurationFailure
	} else {
		ko.Status.SmsConfigurationFailure = nil
	}
	if resp.UserPool.SmsVerificationMessage != nil {
		ko.Spec.SmsVerificationMessage = resp.UserPool.SmsVerificationMessage
	} else {
		ko.Spec.SmsVerificationMessage = nil
	}
	if resp.UserPool.Status != "" {
		ko.Status.Status = aws.String(string(resp.UserPool.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.UserPool.UserAttributeUpdateSettings != nil {
		f29 := &svcapitypes.UserAttributeUpdateSettingsType{}
		if resp.UserPool.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate != nil {
			f29f0 := []*string{}
			for _, f29f0iter := range resp.UserPool.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate {
				var f29f0elem *string
				f29f0elem = aws.String(string(f29f0iter))
				f29f0 = append(f29f0, f29f0elem)
			}
			f29.AttributesRequireVerificationBeforeUpdate = f29f0
		}
		ko.Spec.UserAttributeUpdateSettings = f29
	} else {
		ko.Spec.UserAttributeUpdateSettings = nil
	}
	if resp.UserPool.UserPoolAddOns != nil {
		f30 := &svcapitypes.UserPoolAddOnsType{}
		if resp.UserPool.UserPoolAddOns.AdvancedSecurityMode != "" {
			f30.AdvancedSecurityMode = aws.String(string(resp.UserPool.UserPoolAddOns.AdvancedSecurityMode))
		}
		ko.Spec.UserPoolAddOns = f30
	} else {
		ko.Spec.UserPoolAddOns = nil
	}
	if resp.UserPool.UserPoolTags != nil {
		ko.Spec.UserPoolTags = aws.StringMap(resp.UserPool.UserPoolTags)
	} else {
		ko.Spec.UserPoolTags = nil
	}
	if resp.UserPool.UsernameAttributes != nil {
		f32 := []*string{}
		for _, f32iter := range resp.UserPool.UsernameAttributes {
			var f32elem *string
			f32elem = aws.String(string(f32iter))
			f32 = append(f32, f32elem)
		}
		ko.Spec.UsernameAttributes = f32
	} else {
		ko.Spec.UsernameAttributes = nil
	}
	if resp.UserPool.UsernameConfiguration != nil {
		f33 := &svcapitypes.UsernameConfigurationType{}
		if resp.UserPool.UsernameConfiguration.CaseSensitive != nil {
			f33.CaseSensitive = resp.UserPool.UsernameConfiguration.CaseSensitive
		}
		ko.Spec.UsernameConfiguration = f33
	} else {
		ko.Spec.UsernameConfiguration = nil
	}
	if resp.UserPool.VerificationMessageTemplate != nil {
		f34 := &svcapitypes.VerificationMessageTemplateType{}
		if resp.UserPool.VerificationMessageTemplate.DefaultEmailOption != "" {
			f34.DefaultEmailOption = aws.String(string(resp.UserPool.VerificationMessageTemplate.DefaultEmailOption))
		}
		if resp.UserPool.VerificationMessageTemplate.EmailMessage != nil {
			f34.EmailMessage = resp.UserPool.VerificationMessageTemplate.EmailMessage
		}
		if resp.UserPool.VerificationMessageTemplate.EmailMessageByLink != nil {
			f34.EmailMessageByLink = resp.UserPool.VerificationMessageTemplate.EmailMessageByLink
		}
		if resp.UserPool.VerificationMessageTemplate.EmailSubject != nil {
			f34.EmailSubject = resp.UserPool.VerificationMessageTemplate.EmailSubject
		}
		if resp.UserPool.VerificationMessageTemplate.EmailSubjectByLink != nil {
			f34.EmailSubjectByLink = resp.UserPool.VerificationMessageTemplate.EmailSubjectByLink
		}
		if resp.UserPool.VerificationMessageTemplate.SmsMessage != nil {
			f34.SmsMessage = resp.UserPool.VerificationMessageTemplate.SmsMessage
		}
		ko.Spec.VerificationMessageTemplate = f34
	} else {
		ko.Spec.VerificationMessageTemplate = nil
	}

	rm.setStatusDefaults(ko)
	err = rm.SyncTags(ctx, string(*ko.Status.ACKResourceMetadata.ARN), desired.ko.Spec.Tags, ko.Spec.Tags)
	if err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateUserPoolInput, error) {
	res := &svcsdk.CreateUserPoolInput{}

	if r.ko.Spec.AccountRecoverySetting != nil {
		f0 := &svcsdktypes.AccountRecoverySettingType{}
		if r.ko.Spec.AccountRecoverySetting.RecoveryMechanisms != nil {
			f0f0 := []svcsdktypes.RecoveryOptionType{}
			for _, f0f0iter := range r.ko.Spec.AccountRecoverySetting.RecoveryMechanisms {
				f0f0elem := &svcsdktypes.RecoveryOptionType{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = svcsdktypes.RecoveryOptionNameType(*f0f0iter.Name)
				}
				if f0f0iter.Priority != nil {
					priorityCopy0 := *f0f0iter.Priority
					if priorityCopy0 > math.MaxInt32 || priorityCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Priority is of type int32")
					}
					priorityCopy := int32(priorityCopy0)
					f0f0elem.Priority = &priorityCopy
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.RecoveryMechanisms = f0f0
		}
		res.AccountRecoverySetting = f0
	}
	if r.ko.Spec.AdminCreateUserConfig != nil {
		f1 := &svcsdktypes.AdminCreateUserConfigType{}
		if r.ko.Spec.AdminCreateUserConfig.AllowAdminCreateUserOnly != nil {
			f1.AllowAdminCreateUserOnly = *r.ko.Spec.AdminCreateUserConfig.AllowAdminCreateUserOnly
		}
		if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate != nil {
			f1f1 := &svcsdktypes.MessageTemplateType{}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage != nil {
				f1f1.EmailMessage = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage
			}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject != nil {
				f1f1.EmailSubject = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject
			}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage != nil {
				f1f1.SMSMessage = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage
			}
			f1.InviteMessageTemplate = f1f1
		}
		if r.ko.Spec.AdminCreateUserConfig.UnusedAccountValidityDays != nil {
			unusedAccountValidityDaysCopy0 := *r.ko.Spec.AdminCreateUserConfig.UnusedAccountValidityDays
			if unusedAccountValidityDaysCopy0 > math.MaxInt32 || unusedAccountValidityDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field UnusedAccountValidityDays is of type int32")
			}
			unusedAccountValidityDaysCopy := int32(unusedAccountValidityDaysCopy0)
			f1.UnusedAccountValidityDays = unusedAccountValidityDaysCopy
		}
		res.AdminCreateUserConfig = f1
	}
	if r.ko.Spec.AliasAttributes != nil {
		f2 := []svcsdktypes.AliasAttributeType{}
		for _, f2iter := range r.ko.Spec.AliasAttributes {
			var f2elem string
			f2elem = string(*f2iter)
			f2 = append(f2, svcsdktypes.AliasAttributeType(f2elem))
		}
		res.AliasAttributes = f2
	}
	if r.ko.Spec.AutoVerifiedAttributes != nil {
		f3 := []svcsdktypes.VerifiedAttributeType{}
		for _, f3iter := range r.ko.Spec.AutoVerifiedAttributes {
			var f3elem string
			f3elem = string(*f3iter)
			f3 = append(f3, svcsdktypes.VerifiedAttributeType(f3elem))
		}
		res.AutoVerifiedAttributes = f3
	}
	if r.ko.Spec.DeletionProtection != nil {
		res.DeletionProtection = svcsdktypes.DeletionProtectionType(*r.ko.Spec.DeletionProtection)
	}
	if r.ko.Spec.DeviceConfiguration != nil {
		f5 := &svcsdktypes.DeviceConfigurationType{}
		if r.ko.Spec.DeviceConfiguration.ChallengeRequiredOnNewDevice != nil {
			f5.ChallengeRequiredOnNewDevice = *r.ko.Spec.DeviceConfiguration.ChallengeRequiredOnNewDevice
		}
		if r.ko.Spec.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt != nil {
			f5.DeviceOnlyRememberedOnUserPrompt = *r.ko.Spec.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt
		}
		res.DeviceConfiguration = f5
	}
	if r.ko.Spec.EmailConfiguration != nil {
		f6 := &svcsdktypes.EmailConfigurationType{}
		if r.ko.Spec.EmailConfiguration.ConfigurationSet != nil {
			f6.ConfigurationSet = r.ko.Spec.EmailConfiguration.ConfigurationSet
		}
		if r.ko.Spec.EmailConfiguration.EmailSendingAccount != nil {
			f6.EmailSendingAccount = svcsdktypes.EmailSendingAccountType(*r.ko.Spec.EmailConfiguration.EmailSendingAccount)
		}
		if r.ko.Spec.EmailConfiguration.From != nil {
			f6.From = r.ko.Spec.EmailConfiguration.From
		}
		if r.ko.Spec.EmailConfiguration.ReplyToEmailAddress != nil {
			f6.ReplyToEmailAddress = r.ko.Spec.EmailConfiguration.ReplyToEmailAddress
		}
		if r.ko.Spec.EmailConfiguration.SourceARN != nil {
			f6.SourceArn = r.ko.Spec.EmailConfiguration.SourceARN
		}
		res.EmailConfiguration = f6
	}
	if r.ko.Spec.EmailVerificationMessage != nil {
		res.EmailVerificationMessage = r.ko.Spec.EmailVerificationMessage
	}
	if r.ko.Spec.EmailVerificationSubject != nil {
		res.EmailVerificationSubject = r.ko.Spec.EmailVerificationSubject
	}
	if r.ko.Spec.IssuerConfiguration != nil {
		f9 := &svcsdktypes.IssuerConfigurationType{}
		if r.ko.Spec.IssuerConfiguration.Type != nil {
			f9.Type = svcsdktypes.IssuerType(*r.ko.Spec.IssuerConfiguration.Type)
		}
		res.IssuerConfiguration = f9
	}
	if r.ko.Spec.KeyConfiguration != nil {
		f10 := &svcsdktypes.KeyConfigurationType{}
		if r.ko.Spec.KeyConfiguration.KeyType != nil {
			f10.KeyType = svcsdktypes.EncryptionKeyType(*r.ko.Spec.KeyConfiguration.KeyType)
		}
		if r.ko.Spec.KeyConfiguration.KMSKeyARN != nil {
			f10.KmsKeyArn = r.ko.Spec.KeyConfiguration.KMSKeyARN
		}
		res.KeyConfiguration = f10
	}
	if r.ko.Spec.LambdaConfig != nil {
		f11 := &svcsdktypes.LambdaConfigType{}
		if r.ko.Spec.LambdaConfig.CreateAuthChallenge != nil {
			f11.CreateAuthChallenge = r.ko.Spec.LambdaConfig.CreateAuthChallenge
		}
		if r.ko.Spec.LambdaConfig.CustomEmailSender != nil {
			f11f1 := &svcsdktypes.CustomEmailLambdaVersionConfigType{}
			if r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaARN != nil {
				f11f1.LambdaArn = r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaVersion != nil {
				f11f1.LambdaVersion = svcsdktypes.CustomEmailSenderLambdaVersionType(*r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaVersion)
			}
			f11.CustomEmailSender = f11f1
		}
		if r.ko.Spec.LambdaConfig.CustomMessage != nil {
			f11.CustomMessage = r.ko.Spec.LambdaConfig.CustomMessage
		}
		if r.ko.Spec.LambdaConfig.CustomSMSSender != nil {
			f11f3 := &svcsdktypes.CustomSMSLambdaVersionConfigType{}
			if r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaARN != nil {
				f11f3.LambdaArn = r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaVersion != nil {
				f11f3.LambdaVersion = svcsdktypes.CustomSMSSenderLambdaVersionType(*r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaVersion)
			}
			f11.CustomSMSSender = f11f3
		}
		if r.ko.Spec.LambdaConfig.DefineAuthChallenge != nil {
			f11.DefineAuthChallenge = r.ko.Spec.LambdaConfig.DefineAuthChallenge
		}
		if r.ko.Spec.LambdaConfig.InboundFederation != nil {
			f11f5 := &svcsdktypes.InboundFederationLambdaType{}
			if r.ko.Spec.LambdaConfig.InboundFederation.LambdaARN != nil {
				f11f5.LambdaArn = r.ko.Spec.LambdaConfig.InboundFederation.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.InboundFederation.LambdaVersion != nil {
				f11f5.LambdaVersion = svcsdktypes.InboundFederationLambdaVersionType(*r.ko.Spec.LambdaConfig.InboundFederation.LambdaVersion)
			}
			f11.InboundFederation = f11f5
		}
		if r.ko.Spec.LambdaConfig.KMSKeyID != nil {
			f11.KMSKeyID = r.ko.Spec.LambdaConfig.KMSKeyID
		}
		if r.ko.Spec.LambdaConfig.PostAuthentication != nil {
			f11.PostAuthentication = r.ko.Spec.LambdaConfig.PostAuthentication
		}
		if r.ko.Spec.LambdaConfig.PostConfirmation != nil {
			f11.PostConfirmation = r.ko.Spec.LambdaConfig.PostConfirmation
		}
		if r.ko.Spec.LambdaConfig.PreAuthentication != nil {
			f11.PreAuthentication = r.ko.Spec.LambdaConfig.PreAuthentication
		}
		if r.ko.Spec.LambdaConfig.PreSignUp != nil {
			f11.PreSignUp = r.ko.Spec.LambdaConfig.PreSignUp
		}
		if r.ko.Spec.LambdaConfig.PreTokenGeneration != nil {
			f11.PreTokenGeneration = r.ko.Spec.LambdaConfig.PreTokenGeneration
		}
		if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig != nil {
			f11f12 := &svcsdktypes.PreTokenGenerationVersionConfigType{}
			if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaARN != nil {
				f11f12.LambdaArn = r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaVersion != nil {
				f11f12.LambdaVersion = svcsdktypes.PreTokenGenerationLambdaVersionType(*r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaVersion)
			}
			f11.PreTokenGenerationConfig = f11f12
		}
		if r.ko.Spec.LambdaConfig.UserMigration != nil {
			f11.UserMigration = r.ko.Spec.LambdaConfig.UserMigration
		}
		if r.ko.Spec.LambdaConfig.VerifyAuthChallengeResponse != nil {
			f11.VerifyAuthChallengeResponse = r.ko.Spec.LambdaConfig.VerifyAuthChallengeResponse
		}
		res.LambdaConfig = f11
	}
	if r.ko.Spec.MFAConfiguration != nil {
		res.MfaConfiguration = svcsdktypes.UserPoolMfaType(*r.ko.Spec.MFAConfiguration)
	}
	if r.ko.Spec.Policies != nil {
		f13 := &svcsdktypes.UserPoolPolicyType{}
		if r.ko.Spec.Policies.PasswordPolicy != nil {
			f13f0 := &svcsdktypes.PasswordPolicyType{}
			if r.ko.Spec.Policies.PasswordPolicy.MinimumLength != nil {
				minimumLengthCopy0 := *r.ko.Spec.Policies.PasswordPolicy.MinimumLength
				if minimumLengthCopy0 > math.MaxInt32 || minimumLengthCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MinimumLength is of type int32")
				}
				minimumLengthCopy := int32(minimumLengthCopy0)
				f13f0.MinimumLength = &minimumLengthCopy
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireLowercase != nil {
				f13f0.RequireLowercase = *r.ko.Spec.Policies.PasswordPolicy.RequireLowercase
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireNumbers != nil {
				f13f0.RequireNumbers = *r.ko.Spec.Policies.PasswordPolicy.RequireNumbers
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireSymbols != nil {
				f13f0.RequireSymbols = *r.ko.Spec.Policies.PasswordPolicy.RequireSymbols
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireUppercase != nil {
				f13f0.RequireUppercase = *r.ko.Spec.Policies.PasswordPolicy.RequireUppercase
			}
			if r.ko.Spec.Policies.PasswordPolicy.TemporaryPasswordValidityDays != nil {
				temporaryPasswordValidityDaysCopy0 := *r.ko.Spec.Policies.PasswordPolicy.TemporaryPasswordValidityDays
				if temporaryPasswordValidityDaysCopy0 > math.MaxInt32 || temporaryPasswordValidityDaysCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field TemporaryPasswordValidityDays is of type int32")
				}
				temporaryPasswordValidityDaysCopy := int32(temporaryPasswordValidityDaysCopy0)
				f13f0.TemporaryPasswordValidityDays = temporaryPasswordValidityDaysCopy
			}
			f13.PasswordPolicy = f13f0
		}
		res.Policies = f13
	}
	if r.ko.Spec.Name != nil {
		res.PoolName = r.ko.Spec.Name
	}
	if r.ko.Spec.Schema != nil {
		f15 := []svcsdktypes.SchemaAttributeType{}
		for _, f15iter := range r.ko.Spec.Schema {
			f15elem := &svcsdktypes.SchemaAttributeType{}
			if f15iter.AttributeDataType != nil {
				f15elem.AttributeDataType = svcsdktypes.AttributeDataType(*f15iter.AttributeDataType)
			}
			if f15iter.DeveloperOnlyAttribute != nil {
				f15elem.DeveloperOnlyAttribute = f15iter.DeveloperOnlyAttribute
			}
			if f15iter.Mutable != nil {
				f15elem.Mutable = f15iter.Mutable
			}
			if f15iter.Name != nil {
				f15elem.Name = f15iter.Name
			}
			if f15iter.NumberAttributeConstraints != nil {
				f15elemf4 := &svcsdktypes.NumberAttributeConstraintsType{}
				if f15iter.NumberAttributeConstraints.MaxValue != nil {
					f15elemf4.MaxValue = f15iter.NumberAttributeConstraints.MaxValue
				}
				if f15iter.NumberAttributeConstraints.MinValue != nil {
					f15elemf4.MinValue = f15iter.NumberAttributeConstraints.MinValue
				}
				f15elem.NumberAttributeConstraints = f15elemf4
			}
			if f15iter.Required != nil {
				f15elem.Required = f15iter.Required
			}
			if f15iter.StringAttributeConstraints != nil {
				f15elemf6 := &svcsdktypes.StringAttributeConstraintsType{}
				if f15iter.StringAttributeConstraints.MaxLength != nil {
					f15elemf6.MaxLength = f15iter.StringAttributeConstraints.MaxLength
				}
				if f15iter.StringAttributeConstraints.MinLength != nil {
					f15elemf6.MinLength = f15iter.StringAttributeConstraints.MinLength
				}
				f15elem.StringAttributeConstraints = f15elemf6
			}
			f15 = append(f15, *f15elem)
		}
		res.Schema = f15
	}
	if r.ko.Spec.SmsAuthenticationMessage != nil {
		res.SmsAuthenticationMessage = r.ko.Spec.SmsAuthenticationMessage
	}
	if r.ko.Spec.SmsConfiguration != nil {
		f17 := &svcsdktypes.SmsConfigurationType{}
		if r.ko.Spec.SmsConfiguration.EumsSms != nil {
			f17f0 := &svcsdktypes.EumsSmsConfigurationType{}
			if r.ko.Spec.SmsConfiguration.EumsSms.CallerARN != nil {
				f17f0.CallerArn = r.ko.Spec.SmsConfiguration.EumsSms.CallerARN
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.ConfigurationSetName != nil {
				f17f0.ConfigurationSetName = r.ko.Spec.SmsConfiguration.EumsSms.ConfigurationSetName
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.ExternalID != nil {
				f17f0.ExternalId = r.ko.Spec.SmsConfiguration.EumsSms.ExternalID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.InEntityID != nil {
				f17f0.InEntityId = r.ko.Spec.SmsConfiguration.EumsSms.InEntityID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.InTemplateID != nil {
				f17f0.InTemplateId = r.ko.Spec.SmsConfiguration.EumsSms.InTemplateID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.OriginationIdentity != nil {
				f17f0.OriginationIdentity = r.ko.Spec.SmsConfiguration.EumsSms.OriginationIdentity
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.Region != nil {
				f17f0.Region = r.ko.Spec.SmsConfiguration.EumsSms.Region
			}
			f17.EumsSms = f17f0
		}
		if r.ko.Spec.SmsConfiguration.ExternalID != nil {
			f17.ExternalId = r.ko.Spec.SmsConfiguration.ExternalID
		}
		if r.ko.Spec.SmsConfiguration.SNSCallerARN != nil {
			f17.SnsCallerArn = r.ko.Spec.SmsConfiguration.SNSCallerARN
		}
		if r.ko.Spec.SmsConfiguration.SNSRegion != nil {
			f17.SnsRegion = r.ko.Spec.SmsConfiguration.SNSRegion
		}
		res.SmsConfiguration = f17
	}
	if r.ko.Spec.SmsVerificationMessage != nil {
		res.SmsVerificationMessage = r.ko.Spec.SmsVerificationMessage
	}
	if r.ko.Spec.UserAttributeUpdateSettings != nil {
		f19 := &svcsdktypes.UserAttributeUpdateSettingsType{}
		if r.ko.Spec.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate != nil {
			f19f0 := []svcsdktypes.VerifiedAttributeType{}
			for _, f19f0iter := range r.ko.Spec.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate {
				var f19f0elem string
				f19f0elem = string(*f19f0iter)
				f19f0 = append(f19f0, svcsdktypes.VerifiedAttributeType(f19f0elem))
			}
			f19.AttributesRequireVerificationBeforeUpdate = f19f0
		}
		res.UserAttributeUpdateSettings = f19
	}
	if r.ko.Spec.UserPoolAddOns != nil {
		f20 := &svcsdktypes.UserPoolAddOnsType{}
		if r.ko.Spec.UserPoolAddOns.AdvancedSecurityMode != nil {
			f20.AdvancedSecurityMode = svcsdktypes.AdvancedSecurityModeType(*r.ko.Spec.UserPoolAddOns.AdvancedSecurityMode)
		}
		res.UserPoolAddOns = f20
	}
	if r.ko.Spec.UserPoolTags != nil {
		res.UserPoolTags = aws.ToStringMap(r.ko.Spec.UserPoolTags)
	}
	if r.ko.Spec.UsernameAttributes != nil {
		f22 := []svcsdktypes.UsernameAttributeType{}
		for _, f22iter := range r.ko.Spec.UsernameAttributes {
			var f22elem string
			f22elem = string(*f22iter)
			f22 = append(f22, svcsdktypes.UsernameAttributeType(f22elem))
		}
		res.UsernameAttributes = f22
	}
	if r.ko.Spec.UsernameConfiguration != nil {
		f23 := &svcsdktypes.UsernameConfigurationType{}
		if r.ko.Spec.UsernameConfiguration.CaseSensitive != nil {
			f23.CaseSensitive = r.ko.Spec.UsernameConfiguration.CaseSensitive
		}
		res.UsernameConfiguration = f23
	}
	if r.ko.Spec.VerificationMessageTemplate != nil {
		f24 := &svcsdktypes.VerificationMessageTemplateType{}
		if r.ko.Spec.VerificationMessageTemplate.DefaultEmailOption != nil {
			f24.DefaultEmailOption = svcsdktypes.DefaultEmailOptionType(*r.ko.Spec.VerificationMessageTemplate.DefaultEmailOption)
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailMessage != nil {
			f24.EmailMessage = r.ko.Spec.VerificationMessageTemplate.EmailMessage
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailMessageByLink != nil {
			f24.EmailMessageByLink = r.ko.Spec.VerificationMessageTemplate.EmailMessageByLink
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailSubject != nil {
			f24.EmailSubject = r.ko.Spec.VerificationMessageTemplate.EmailSubject
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailSubjectByLink != nil {
			f24.EmailSubjectByLink = r.ko.Spec.VerificationMessageTemplate.EmailSubjectByLink
		}
		if r.ko.Spec.VerificationMessageTemplate.SmsMessage != nil {
			f24.SmsMessage = r.ko.Spec.VerificationMessageTemplate.SmsMessage
		}
		res.VerificationMessageTemplate = f24
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.SyncTags(
			ctx,
			string(*latest.ko.Status.ACKResourceMetadata.ARN),
			desired.ko.Spec.Tags,
			latest.ko.Spec.Tags,
		); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateUserPoolOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateUserPool(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateUserPool", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateUserPoolInput, error) {
	res := &svcsdk.UpdateUserPoolInput{}

	if r.ko.Spec.AccountRecoverySetting != nil {
		f0 := &svcsdktypes.AccountRecoverySettingType{}
		if r.ko.Spec.AccountRecoverySetting.RecoveryMechanisms != nil {
			f0f0 := []svcsdktypes.RecoveryOptionType{}
			for _, f0f0iter := range r.ko.Spec.AccountRecoverySetting.RecoveryMechanisms {
				f0f0elem := &svcsdktypes.RecoveryOptionType{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = svcsdktypes.RecoveryOptionNameType(*f0f0iter.Name)
				}
				if f0f0iter.Priority != nil {
					priorityCopy0 := *f0f0iter.Priority
					if priorityCopy0 > math.MaxInt32 || priorityCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field Priority is of type int32")
					}
					priorityCopy := int32(priorityCopy0)
					f0f0elem.Priority = &priorityCopy
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.RecoveryMechanisms = f0f0
		}
		res.AccountRecoverySetting = f0
	}
	if r.ko.Spec.AdminCreateUserConfig != nil {
		f1 := &svcsdktypes.AdminCreateUserConfigType{}
		if r.ko.Spec.AdminCreateUserConfig.AllowAdminCreateUserOnly != nil {
			f1.AllowAdminCreateUserOnly = *r.ko.Spec.AdminCreateUserConfig.AllowAdminCreateUserOnly
		}
		if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate != nil {
			f1f1 := &svcsdktypes.MessageTemplateType{}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage != nil {
				f1f1.EmailMessage = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailMessage
			}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject != nil {
				f1f1.EmailSubject = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.EmailSubject
			}
			if r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage != nil {
				f1f1.SMSMessage = r.ko.Spec.AdminCreateUserConfig.InviteMessageTemplate.SMSMessage
			}
			f1.InviteMessageTemplate = f1f1
		}
		if r.ko.Spec.AdminCreateUserConfig.UnusedAccountValidityDays != nil {
			unusedAccountValidityDaysCopy0 := *r.ko.Spec.AdminCreateUserConfig.UnusedAccountValidityDays
			if unusedAccountValidityDaysCopy0 > math.MaxInt32 || unusedAccountValidityDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field UnusedAccountValidityDays is of type int32")
			}
			unusedAccountValidityDaysCopy := int32(unusedAccountValidityDaysCopy0)
			f1.UnusedAccountValidityDays = unusedAccountValidityDaysCopy
		}
		res.AdminCreateUserConfig = f1
	}
	if r.ko.Spec.AutoVerifiedAttributes != nil {
		f2 := []svcsdktypes.VerifiedAttributeType{}
		for _, f2iter := range r.ko.Spec.AutoVerifiedAttributes {
			var f2elem string
			f2elem = string(*f2iter)
			f2 = append(f2, svcsdktypes.VerifiedAttributeType(f2elem))
		}
		res.AutoVerifiedAttributes = f2
	}
	if r.ko.Spec.DeletionProtection != nil {
		res.DeletionProtection = svcsdktypes.DeletionProtectionType(*r.ko.Spec.DeletionProtection)
	}
	if r.ko.Spec.DeviceConfiguration != nil {
		f4 := &svcsdktypes.DeviceConfigurationType{}
		if r.ko.Spec.DeviceConfiguration.ChallengeRequiredOnNewDevice != nil {
			f4.ChallengeRequiredOnNewDevice = *r.ko.Spec.DeviceConfiguration.ChallengeRequiredOnNewDevice
		}
		if r.ko.Spec.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt != nil {
			f4.DeviceOnlyRememberedOnUserPrompt = *r.ko.Spec.DeviceConfiguration.DeviceOnlyRememberedOnUserPrompt
		}
		res.DeviceConfiguration = f4
	}
	if r.ko.Spec.EmailConfiguration != nil {
		f5 := &svcsdktypes.EmailConfigurationType{}
		if r.ko.Spec.EmailConfiguration.ConfigurationSet != nil {
			f5.ConfigurationSet = r.ko.Spec.EmailConfiguration.ConfigurationSet
		}
		if r.ko.Spec.EmailConfiguration.EmailSendingAccount != nil {
			f5.EmailSendingAccount = svcsdktypes.EmailSendingAccountType(*r.ko.Spec.EmailConfiguration.EmailSendingAccount)
		}
		if r.ko.Spec.EmailConfiguration.From != nil {
			f5.From = r.ko.Spec.EmailConfiguration.From
		}
		if r.ko.Spec.EmailConfiguration.ReplyToEmailAddress != nil {
			f5.ReplyToEmailAddress = r.ko.Spec.EmailConfiguration.ReplyToEmailAddress
		}
		if r.ko.Spec.EmailConfiguration.SourceARN != nil {
			f5.SourceArn = r.ko.Spec.EmailConfiguration.SourceARN
		}
		res.EmailConfiguration = f5
	}
	if r.ko.Spec.EmailVerificationMessage != nil {
		res.EmailVerificationMessage = r.ko.Spec.EmailVerificationMessage
	}
	if r.ko.Spec.EmailVerificationSubject != nil {
		res.EmailVerificationSubject = r.ko.Spec.EmailVerificationSubject
	}
	if r.ko.Spec.IssuerConfiguration != nil {
		f8 := &svcsdktypes.IssuerConfigurationType{}
		if r.ko.Spec.IssuerConfiguration.Type != nil {
			f8.Type = svcsdktypes.IssuerType(*r.ko.Spec.IssuerConfiguration.Type)
		}
		res.IssuerConfiguration = f8
	}
	if r.ko.Spec.KeyConfiguration != nil {
		f9 := &svcsdktypes.KeyConfigurationType{}
		if r.ko.Spec.KeyConfiguration.KeyType != nil {
			f9.KeyType = svcsdktypes.EncryptionKeyType(*r.ko.Spec.KeyConfiguration.KeyType)
		}
		if r.ko.Spec.KeyConfiguration.KMSKeyARN != nil {
			f9.KmsKeyArn = r.ko.Spec.KeyConfiguration.KMSKeyARN
		}
		res.KeyConfiguration = f9
	}
	if r.ko.Spec.LambdaConfig != nil {
		f10 := &svcsdktypes.LambdaConfigType{}
		if r.ko.Spec.LambdaConfig.CreateAuthChallenge != nil {
			f10.CreateAuthChallenge = r.ko.Spec.LambdaConfig.CreateAuthChallenge
		}
		if r.ko.Spec.LambdaConfig.CustomEmailSender != nil {
			f10f1 := &svcsdktypes.CustomEmailLambdaVersionConfigType{}
			if r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaARN != nil {
				f10f1.LambdaArn = r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaVersion != nil {
				f10f1.LambdaVersion = svcsdktypes.CustomEmailSenderLambdaVersionType(*r.ko.Spec.LambdaConfig.CustomEmailSender.LambdaVersion)
			}
			f10.CustomEmailSender = f10f1
		}
		if r.ko.Spec.LambdaConfig.CustomMessage != nil {
			f10.CustomMessage = r.ko.Spec.LambdaConfig.CustomMessage
		}
		if r.ko.Spec.LambdaConfig.CustomSMSSender != nil {
			f10f3 := &svcsdktypes.CustomSMSLambdaVersionConfigType{}
			if r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaARN != nil {
				f10f3.LambdaArn = r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaVersion != nil {
				f10f3.LambdaVersion = svcsdktypes.CustomSMSSenderLambdaVersionType(*r.ko.Spec.LambdaConfig.CustomSMSSender.LambdaVersion)
			}
			f10.CustomSMSSender = f10f3
		}
		if r.ko.Spec.LambdaConfig.DefineAuthChallenge != nil {
			f10.DefineAuthChallenge = r.ko.Spec.LambdaConfig.DefineAuthChallenge
		}
		if r.ko.Spec.LambdaConfig.InboundFederation != nil {
			f10f5 := &svcsdktypes.InboundFederationLambdaType{}
			if r.ko.Spec.LambdaConfig.InboundFederation.LambdaARN != nil {
				f10f5.LambdaArn = r.ko.Spec.LambdaConfig.InboundFederation.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.InboundFederation.LambdaVersion != nil {
				f10f5.LambdaVersion = svcsdktypes.InboundFederationLambdaVersionType(*r.ko.Spec.LambdaConfig.InboundFederation.LambdaVersion)
			}
			f10.InboundFederation = f10f5
		}
		if r.ko.Spec.LambdaConfig.KMSKeyID != nil {
			f10.KMSKeyID = r.ko.Spec.LambdaConfig.KMSKeyID
		}
		if r.ko.Spec.LambdaConfig.PostAuthentication != nil {
			f10.PostAuthentication = r.ko.Spec.LambdaConfig.PostAuthentication
		}
		if r.ko.Spec.LambdaConfig.PostConfirmation != nil {
			f10.PostConfirmation = r.ko.Spec.LambdaConfig.PostConfirmation
		}
		if r.ko.Spec.LambdaConfig.PreAuthentication != nil {
			f10.PreAuthentication = r.ko.Spec.LambdaConfig.PreAuthentication
		}
		if r.ko.Spec.LambdaConfig.PreSignUp != nil {
			f10.PreSignUp = r.ko.Spec.LambdaConfig.PreSignUp
		}
		if r.ko.Spec.LambdaConfig.PreTokenGeneration != nil {
			f10.PreTokenGeneration = r.ko.Spec.LambdaConfig.PreTokenGeneration
		}
		if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig != nil {
			f10f12 := &svcsdktypes.PreTokenGenerationVersionConfigType{}
			if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaARN != nil {
				f10f12.LambdaArn = r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaARN
			}
			if r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaVersion != nil {
				f10f12.LambdaVersion = svcsdktypes.PreTokenGenerationLambdaVersionType(*r.ko.Spec.LambdaConfig.PreTokenGenerationConfig.LambdaVersion)
			}
			f10.PreTokenGenerationConfig = f10f12
		}
		if r.ko.Spec.LambdaConfig.UserMigration != nil {
			f10.UserMigration = r.ko.Spec.LambdaConfig.UserMigration
		}
		if r.ko.Spec.LambdaConfig.VerifyAuthChallengeResponse != nil {
			f10.VerifyAuthChallengeResponse = r.ko.Spec.LambdaConfig.VerifyAuthChallengeResponse
		}
		res.LambdaConfig = f10
	}
	if r.ko.Spec.MFAConfiguration != nil {
		res.MfaConfiguration = svcsdktypes.UserPoolMfaType(*r.ko.Spec.MFAConfiguration)
	}
	if r.ko.Spec.Policies != nil {
		f12 := &svcsdktypes.UserPoolPolicyType{}
		if r.ko.Spec.Policies.PasswordPolicy != nil {
			f12f0 := &svcsdktypes.PasswordPolicyType{}
			if r.ko.Spec.Policies.PasswordPolicy.MinimumLength != nil {
				minimumLengthCopy0 := *r.ko.Spec.Policies.PasswordPolicy.MinimumLength
				if minimumLengthCopy0 > math.MaxInt32 || minimumLengthCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field MinimumLength is of type int32")
				}
				minimumLengthCopy := int32(minimumLengthCopy0)
				f12f0.MinimumLength = &minimumLengthCopy
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireLowercase != nil {
				f12f0.RequireLowercase = *r.ko.Spec.Policies.PasswordPolicy.RequireLowercase
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireNumbers != nil {
				f12f0.RequireNumbers = *r.ko.Spec.Policies.PasswordPolicy.RequireNumbers
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireSymbols != nil {
				f12f0.RequireSymbols = *r.ko.Spec.Policies.PasswordPolicy.RequireSymbols
			}
			if r.ko.Spec.Policies.PasswordPolicy.RequireUppercase != nil {
				f12f0.RequireUppercase = *r.ko.Spec.Policies.PasswordPolicy.RequireUppercase
			}
			if r.ko.Spec.Policies.PasswordPolicy.TemporaryPasswordValidityDays != nil {
				temporaryPasswordValidityDaysCopy0 := *r.ko.Spec.Policies.PasswordPolicy.TemporaryPasswordValidityDays
				if temporaryPasswordValidityDaysCopy0 > math.MaxInt32 || temporaryPasswordValidityDaysCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field TemporaryPasswordValidityDays is of type int32")
				}
				temporaryPasswordValidityDaysCopy := int32(temporaryPasswordValidityDaysCopy0)
				f12f0.TemporaryPasswordValidityDays = temporaryPasswordValidityDaysCopy
			}
			f12.PasswordPolicy = f12f0
		}
		res.Policies = f12
	}
	if r.ko.Spec.SmsAuthenticationMessage != nil {
		res.SmsAuthenticationMessage = r.ko.Spec.SmsAuthenticationMessage
	}
	if r.ko.Spec.SmsConfiguration != nil {
		f15 := &svcsdktypes.SmsConfigurationType{}
		if r.ko.Spec.SmsConfiguration.EumsSms != nil {
			f15f0 := &svcsdktypes.EumsSmsConfigurationType{}
			if r.ko.Spec.SmsConfiguration.EumsSms.CallerARN != nil {
				f15f0.CallerArn = r.ko.Spec.SmsConfiguration.EumsSms.CallerARN
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.ConfigurationSetName != nil {
				f15f0.ConfigurationSetName = r.ko.Spec.SmsConfiguration.EumsSms.ConfigurationSetName
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.ExternalID != nil {
				f15f0.ExternalId = r.ko.Spec.SmsConfiguration.EumsSms.ExternalID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.InEntityID != nil {
				f15f0.InEntityId = r.ko.Spec.SmsConfiguration.EumsSms.InEntityID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.InTemplateID != nil {
				f15f0.InTemplateId = r.ko.Spec.SmsConfiguration.EumsSms.InTemplateID
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.OriginationIdentity != nil {
				f15f0.OriginationIdentity = r.ko.Spec.SmsConfiguration.EumsSms.OriginationIdentity
			}
			if r.ko.Spec.SmsConfiguration.EumsSms.Region != nil {
				f15f0.Region = r.ko.Spec.SmsConfiguration.EumsSms.Region
			}
			f15.EumsSms = f15f0
		}
		if r.ko.Spec.SmsConfiguration.ExternalID != nil {
			f15.ExternalId = r.ko.Spec.SmsConfiguration.ExternalID
		}
		if r.ko.Spec.SmsConfiguration.SNSCallerARN != nil {
			f15.SnsCallerArn = r.ko.Spec.SmsConfiguration.SNSCallerARN
		}
		if r.ko.Spec.SmsConfiguration.SNSRegion != nil {
			f15.SnsRegion = r.ko.Spec.SmsConfiguration.SNSRegion
		}
		res.SmsConfiguration = f15
	}
	if r.ko.Spec.SmsVerificationMessage != nil {
		res.SmsVerificationMessage = r.ko.Spec.SmsVerificationMessage
	}
	if r.ko.Spec.UserAttributeUpdateSettings != nil {
		f17 := &svcsdktypes.UserAttributeUpdateSettingsType{}
		if r.ko.Spec.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate != nil {
			f17f0 := []svcsdktypes.VerifiedAttributeType{}
			for _, f17f0iter := range r.ko.Spec.UserAttributeUpdateSettings.AttributesRequireVerificationBeforeUpdate {
				var f17f0elem string
				f17f0elem = string(*f17f0iter)
				f17f0 = append(f17f0, svcsdktypes.VerifiedAttributeType(f17f0elem))
			}
			f17.AttributesRequireVerificationBeforeUpdate = f17f0
		}
		res.UserAttributeUpdateSettings = f17
	}
	if r.ko.Spec.UserPoolAddOns != nil {
		f18 := &svcsdktypes.UserPoolAddOnsType{}
		if r.ko.Spec.UserPoolAddOns.AdvancedSecurityMode != nil {
			f18.AdvancedSecurityMode = svcsdktypes.AdvancedSecurityModeType(*r.ko.Spec.UserPoolAddOns.AdvancedSecurityMode)
		}
		res.UserPoolAddOns = f18
	}
	if r.ko.Status.ID != nil {
		res.UserPoolId = r.ko.Status.ID
	}
	if r.ko.Spec.UserPoolTags != nil {
		res.UserPoolTags = aws.ToStringMap(r.ko.Spec.UserPoolTags)
	}
	if r.ko.Spec.VerificationMessageTemplate != nil {
		f22 := &svcsdktypes.VerificationMessageTemplateType{}
		if r.ko.Spec.VerificationMessageTemplate.DefaultEmailOption != nil {
			f22.DefaultEmailOption = svcsdktypes.DefaultEmailOptionType(*r.ko.Spec.VerificationMessageTemplate.DefaultEmailOption)
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailMessage != nil {
			f22.EmailMessage = r.ko.Spec.VerificationMessageTemplate.EmailMessage
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailMessageByLink != nil {
			f22.EmailMessageByLink = r.ko.Spec.VerificationMessageTemplate.EmailMessageByLink
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailSubject != nil {
			f22.EmailSubject = r.ko.Spec.VerificationMessageTemplate.EmailSubject
		}
		if r.ko.Spec.VerificationMessageTemplate.EmailSubjectByLink != nil {
			f22.EmailSubjectByLink = r.ko.Spec.VerificationMessageTemplate.EmailSubjectByLink
		}
		if r.ko.Spec.VerificationMessageTemplate.SmsMessage != nil {
			f22.SmsMessage = r.ko.Spec.VerificationMessageTemplate.SmsMessage
		}
		res.VerificationMessageTemplate = f22
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteUserPoolOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteUserPool(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteUserPool", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteUserPoolInput, error) {
	res := &svcsdk.DeleteUserPoolInput{}

	if r.ko.Status.ID != nil {
		res.UserPoolId = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.UserPool,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException":
		return true
	default:
		return false
	}
}
