// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = ackv1alpha1.AWSAccountID("")
)

// The settings for user message delivery in forgot-password operations. Contains
// preference for email or SMS message delivery of password reset codes, or
// for admin-only password reset.
type AccountRecoverySettingType struct {
	RecoveryMechanisms []*RecoveryOptionType `json:"recoveryMechanisms,omitempty"`
}

// The settings for administrator creation of users in a user pool. Contains
// settings for allowing user sign-up, customizing invitation messages to new
// users, and the amount of time before temporary passwords expire.
type AdminCreateUserConfigType struct {
	AllowAdminCreateUserOnly *bool `json:"allowAdminCreateUserOnly,omitempty"`
	// The message template structure.
	InviteMessageTemplate     *MessageTemplateType `json:"inviteMessageTemplate,omitempty"`
	UnusedAccountValidityDays *int64               `json:"unusedAccountValidityDays,omitempty"`
}

// The settings for Amazon Pinpoint analytics configuration. With an analytics
// configuration, your application can collect user-activity metrics for user
// notifications with a Amazon Pinpoint campaign.
//
// Amazon Pinpoint isn't available in all Amazon Web Services Regions. For a
// list of available Regions, see Amazon Cognito and Amazon Pinpoint Region
// availability (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html#cognito-user-pools-find-region-mappings).
type AnalyticsConfigurationType struct {
	ApplicationARN *string `json:"applicationARN,omitempty"`
	ApplicationID  *string `json:"applicationID,omitempty"`
	ExternalID     *string `json:"externalID,omitempty"`
	RoleARN        *string `json:"roleARN,omitempty"`
	UserDataShared *bool   `json:"userDataShared,omitempty"`
}

// Information that your application adds to authentication requests. Applies
// an endpoint ID to the analytics data that your user pool sends to Amazon
// Pinpoint.
//
// An endpoint ID uniquely identifies a mobile device, email address or phone
// number that can receive messages from Amazon Pinpoint analytics. For more
// information about Amazon Web Services Regions that can contain Amazon Pinpoint
// resources for use with Amazon Cognito user pools, see Using Amazon Pinpoint
// analytics with Amazon Cognito user pools (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html).
type AnalyticsMetadataType struct {
	AnalyticsEndpointID *string `json:"analyticsEndpointID,omitempty"`
}

// One authentication event that Amazon Cognito logged in a user pool with threat
// protection active. Contains user and device metadata and a risk assessment
// from your user pool.
type AuthEventType struct {
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	EventID      *string      `json:"eventID,omitempty"`
}

// The object that your application receives after authentication. Contains
// tokens and information for device authentication.
type AuthenticationResultType struct {
	ExpiresIn *int64  `json:"expiresIn,omitempty"`
	TokenType *string `json:"tokenType,omitempty"`
}

// The access token and its metadata from a machine-to-machine (M2M) client
// credentials grant.
type ClientAuthenticationResultType struct {
	ExpiresIn *int64  `json:"expiresIn,omitempty"`
	TokenType *string `json:"tokenType,omitempty"`
}

// Contains information about a client secret, including its unique identifier,
// value, and creation timestamp.
type ClientSecretDescriptorType struct {
	ClientSecretCreateDate *metav1.Time `json:"clientSecretCreateDate,omitempty"`
	ClientSecretID         *string      `json:"clientSecretID,omitempty"`
}

// Configuration for the CloudWatch log group destination of user pool detailed
// activity logging, or of user activity log export with threat protection.
type CloudWatchLogsConfigurationType struct {
	LogGroupARN *string `json:"logGroupARN,omitempty"`
}

// The delivery details for an email or SMS message that Amazon Cognito sent
// for authentication or verification.
type CodeDeliveryDetailsType struct {
	Destination *string `json:"destination,omitempty"`
}

// Contextual user data used for evaluating the risk of an authentication event
// by user pool threat protection.
type ContextDataType struct {
	EncodedData *string `json:"encodedData,omitempty"`
	IPAddress   *string `json:"ipAddress,omitempty"`
	ServerName  *string `json:"serverName,omitempty"`
	ServerPath  *string `json:"serverPath,omitempty"`
}

// The configuration for a custom domain, including the SSL certificate and
// TLS security policy.
type CustomDomainConfigType struct {
	CertificateARN *string `json:"certificateARN,omitempty"`
}

// The properties of a custom email sender Lambda trigger.
type CustomEmailLambdaVersionConfigType struct {
	LambdaARN     *string `json:"lambdaARN,omitempty"`
	LambdaVersion *string `json:"lambdaVersion,omitempty"`
}

// The properties of a custom SMS sender Lambda trigger.
type CustomSMSLambdaVersionConfigType struct {
	LambdaARN     *string `json:"lambdaARN,omitempty"`
	LambdaVersion *string `json:"lambdaVersion,omitempty"`
}

// The device-remembering configuration for a user pool.
//
// When you provide a value for any property of DeviceConfiguration, you activate
// the device remembering for the user pool.
type DeviceConfigurationType struct {
	ChallengeRequiredOnNewDevice     *bool `json:"challengeRequiredOnNewDevice,omitempty"`
	DeviceOnlyRememberedOnUserPrompt *bool `json:"deviceOnlyRememberedOnUserPrompt,omitempty"`
}

// A Secure Remote Password (SRP) value that your application generates when
// you register a user's device. For more information, see Getting a device
// key (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html#user-pools-remembered-devices-getting-a-device-key).
type DeviceSecretVerifierConfigType struct {
	PasswordVerifier *string `json:"passwordVerifier,omitempty"`
	Salt             *string `json:"salt,omitempty"`
}

// Information about a user's device that they've registered for device SRP
// authentication in your application. For more information, see Working with
// user devices in your user pool (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html).
type DeviceType struct {
	DeviceCreateDate            *metav1.Time `json:"deviceCreateDate,omitempty"`
	DeviceLastAuthenticatedDate *metav1.Time `json:"deviceLastAuthenticatedDate,omitempty"`
	DeviceLastModifiedDate      *metav1.Time `json:"deviceLastModifiedDate,omitempty"`
}

// A container for information about the user pool domain associated with the
// hosted UI and OAuth endpoints.
type DomainDescriptionType struct {
	CloudFrontDistribution *string `json:"cloudFrontDistribution,omitempty"`
	Domain                 *string `json:"domain,omitempty"`
	UserPoolID             *string `json:"userPoolID,omitempty"`
}

// The email configuration of your user pool. The email configuration type sets
// your preferred sending method, Amazon Web Services Region, and sender for
// messages from your user pool.
//
// Amazon Cognito can send email messages with Amazon Simple Email Service resources
// in the Amazon Web Services Region where you created your user pool, and in
// alternate Regions in some cases. For more information on the supported Regions,
// see Email settings for Amazon Cognito user pools (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html).
type EmailConfigurationType struct {
	ConfigurationSet    *string `json:"configurationSet,omitempty"`
	EmailSendingAccount *string `json:"emailSendingAccount,omitempty"`
	From                *string `json:"from,omitempty"`
	ReplyToEmailAddress *string `json:"replyToEmailAddress,omitempty"`
	SourceARN           *string `json:"sourceARN,omitempty"`
}

// User preferences for multi-factor authentication with email messages. Activates
// or deactivates email MFA and sets it as the preferred MFA method when multiple
// methods are available. To activate this setting, your user pool must be in
// the Essentials tier (https://docs.aws.amazon.com/cognito/latest/developerguide/feature-plans-features-essentials.html)
// or higher.
type EmailMFASettingsType struct {
	Enabled      *bool `json:"enabled,omitempty"`
	PreferredMFA *bool `json:"preferredMFA,omitempty"`
}

// The configuration that Amazon Cognito uses to send SMS messages through Amazon
// Web Services End User Messaging SMS. Provide this structure in the EumsSms
// member of SmsConfigurationType to use Amazon Web Services End User Messaging
// SMS instead of Amazon SNS.
type EumsSmsConfigurationType struct {
	CallerARN            *string `json:"callerARN,omitempty"`
	ConfigurationSetName *string `json:"configurationSetName,omitempty"`
	ExternalID           *string `json:"externalID,omitempty"`
	InEntityID           *string `json:"inEntityID,omitempty"`
	InTemplateID         *string `json:"inTemplateID,omitempty"`
	OriginationIdentity  *string `json:"originationIdentity,omitempty"`
	Region               *string `json:"region,omitempty"`
}

// The context data that your application submitted in an authentication request
// with threat protection, as displayed in an AdminListUserAuthEvents response.
type EventContextDataType struct {
	City       *string `json:"city,omitempty"`
	Country    *string `json:"country,omitempty"`
	DeviceName *string `json:"deviceName,omitempty"`
	IPAddress  *string `json:"ipAddress,omitempty"`
	Timezone   *string `json:"timezone,omitempty"`
}

// The feedback that your application submitted to a threat protection event
// log, as displayed in an AdminListUserAuthEvents response.
type EventFeedbackType struct {
	FeedbackDate *metav1.Time `json:"feedbackDate,omitempty"`
	Provider     *string      `json:"provider,omitempty"`
}

// The risk evaluation by adaptive authentication, as displayed in an AdminListUserAuthEvents
// response. Contains evaluations of compromised-credentials detection and assessed
// risk level and action taken by adaptive authentication.
type EventRiskType struct {
	CompromisedCredentialsDetected *bool `json:"compromisedCredentialsDetected,omitempty"`
}

// Configuration for the Amazon Data Firehose stream destination of user activity
// log export with threat protection.
type FirehoseConfigurationType struct {
	StreamARN *string `json:"streamARN,omitempty"`
}

// A user pool group. Contains details about the group and the way that it contributes
// to IAM role decisions with identity pools. Identity pools can make decisions
// about the IAM role to assign based on groups: users get credentials for the
// role associated with their highest-priority group.
type GroupType struct {
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	RoleARN          *string      `json:"roleARN,omitempty"`
	UserPoolID       *string      `json:"userPoolID,omitempty"`
}

// The HTTP header in the ContextData parameter.
type HTTPHeader struct {
	HeaderName  *string `json:"headerName,omitempty"`
	HeaderValue *string `json:"headerValue,omitempty"`
}

// A user pool identity provider (IdP). Contains information about a third-party
// IdP to a user pool, the attributes that it populates to user profiles, and
// the trust relationship between the IdP and your user pool.
type IdentityProviderType struct {
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	ProviderName     *string      `json:"providerName,omitempty"`
	UserPoolID       *string      `json:"userPoolID,omitempty"`
}

// The properties of an inbound federation Lambda trigger.
type InboundFederationLambdaType struct {
	LambdaARN     *string `json:"lambdaARN,omitempty"`
	LambdaVersion *string `json:"lambdaVersion,omitempty"`
}

// Specifies the issuer configuration for a user pool. Contains settings that
// determine how tokens are issued and validated.
type IssuerConfigurationType struct {
	Type *string `json:"type_,omitempty"`
}

// Specifies the key configuration for a user pool. Contains settings for encryption
// keys used to secure user pool data.
type KeyConfigurationType struct {
	KeyType   *string `json:"keyType,omitempty"`
	KMSKeyARN *string `json:"kmsKeyARN,omitempty"`
}

// A collection of user pool Lambda triggers. Amazon Cognito invokes triggers
// at several possible stages of user pool operations. Triggers can modify the
// outcome of the operations that invoked them.
type LambdaConfigType struct {
	CreateAuthChallenge *string `json:"createAuthChallenge,omitempty"`
	// The properties of a custom email sender Lambda trigger.
	CustomEmailSender *CustomEmailLambdaVersionConfigType `json:"customEmailSender,omitempty"`
	CustomMessage     *string                             `json:"customMessage,omitempty"`
	// The properties of a custom SMS sender Lambda trigger.
	CustomSMSSender     *CustomSMSLambdaVersionConfigType `json:"customSMSSender,omitempty"`
	DefineAuthChallenge *string                           `json:"defineAuthChallenge,omitempty"`
	// The properties of an inbound federation Lambda trigger.
	InboundFederation  *InboundFederationLambdaType `json:"inboundFederation,omitempty"`
	KMSKeyID           *string                      `json:"kmsKeyID,omitempty"`
	PostAuthentication *string                      `json:"postAuthentication,omitempty"`
	PostConfirmation   *string                      `json:"postConfirmation,omitempty"`
	PreAuthentication  *string                      `json:"preAuthentication,omitempty"`
	PreSignUp          *string                      `json:"preSignUp,omitempty"`
	PreTokenGeneration *string                      `json:"preTokenGeneration,omitempty"`
	// The properties of a pre token generation Lambda trigger.
	PreTokenGenerationConfig    *PreTokenGenerationVersionConfigType `json:"preTokenGenerationConfig,omitempty"`
	UserMigration               *string                              `json:"userMigration,omitempty"`
	VerifyAuthChallengeResponse *string                              `json:"verifyAuthChallengeResponse,omitempty"`
}

// The limit definition and current limit values for a provisioned limit.
type LimitType struct {
	FreeLimitValue        *int64 `json:"freeLimitValue,omitempty"`
	ProvisionedLimitValue *int64 `json:"provisionedLimitValue,omitempty"`
}

// The logging parameters of a user pool, as returned in the response to a GetLogDeliveryConfiguration
// request.
type LogDeliveryConfigurationType struct {
	UserPoolID *string `json:"userPoolID,omitempty"`
}

// A managed login branding style that's assigned to a user pool app client.
type ManagedLoginBrandingType struct {
	CreationDate             *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate         *metav1.Time `json:"lastModifiedDate,omitempty"`
	UseCognitoProvidedValues *bool        `json:"useCognitoProvidedValues,omitempty"`
	UserPoolID               *string      `json:"userPoolID,omitempty"`
}

// The message template structure.
type MessageTemplateType struct {
	EmailMessage *string `json:"emailMessage,omitempty"`
	EmailSubject *string `json:"emailSubject,omitempty"`
	SMSMessage   *string `json:"sMSMessage,omitempty"`
}

// Information that your user pool responds with in AuthenticationResultwhen
// you configure it to remember devices and a user signs in with an unrecognized
// device. Amazon Cognito presents a new device key that you can use to set
// up device authentication (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html)
// in a "Remember me on this device" authentication model.
type NewDeviceMetadataType struct {
	DeviceGroupKey *string `json:"deviceGroupKey,omitempty"`
}

// The configuration for Amazon SES email messages that threat protection sends
// to a user when your adaptive authentication automated response has a Notify
// action.
type NotifyConfigurationType struct {
	From      *string `json:"from,omitempty"`
	ReplyTo   *string `json:"replyTo,omitempty"`
	SourceARN *string `json:"sourceARN,omitempty"`
}

// The minimum and maximum values of an attribute that is of the number type,
// for example custom:age.
type NumberAttributeConstraintsType struct {
	MaxValue *string `json:"maxValue,omitempty"`
	MinValue *string `json:"minValue,omitempty"`
}

// The password policy settings for a user pool, including complexity, history,
// and length requirements.
type PasswordPolicyType struct {
	MinimumLength                 *int64 `json:"minimumLength,omitempty"`
	RequireLowercase              *bool  `json:"requireLowercase,omitempty"`
	RequireNumbers                *bool  `json:"requireNumbers,omitempty"`
	RequireSymbols                *bool  `json:"requireSymbols,omitempty"`
	RequireUppercase              *bool  `json:"requireUppercase,omitempty"`
	TemporaryPasswordValidityDays *int64 `json:"temporaryPasswordValidityDays,omitempty"`
}

// The properties of a pre token generation Lambda trigger.
type PreTokenGenerationVersionConfigType struct {
	LambdaARN     *string `json:"lambdaARN,omitempty"`
	LambdaVersion *string `json:"lambdaVersion,omitempty"`
}

// The details of a user pool identity provider (IdP), including name and type.
type ProviderDescription struct {
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	ProviderName     *string      `json:"providerName,omitempty"`
}

// The characteristics of a source or destination user for linking a federated
// user profile to a local user profile.
type ProviderUserIdentifierType struct {
	ProviderAttributeName  *string `json:"providerAttributeName,omitempty"`
	ProviderAttributeValue *string `json:"providerAttributeValue,omitempty"`
	ProviderName           *string `json:"providerName,omitempty"`
}

// A recovery option for a user. The AccountRecoverySettingType data type is
// an array of this object. Each RecoveryOptionType has a priority property
// that determines whether it is a primary or secondary option.
//
// For example, if verified_email has a priority of 1 and verified_phone_number
// has a priority of 2, your user pool sends account-recovery messages to a
// verified email address but falls back to an SMS message if the user has a
// verified phone number. The admin_only option prevents self-service account
// recovery.
type RecoveryOptionType struct {
	Name     *string `json:"name,omitempty"`
	Priority *int64  `json:"priority,omitempty"`
}

// The configuration of your app client for refresh token rotation. When enabled,
// your app client issues new ID, access, and refresh tokens when users renew
// their sessions with refresh tokens. When disabled, token refresh issues only
// ID and access tokens.
type RefreshTokenRotationType struct {
	Feature                 *string `json:"feature,omitempty"`
	RetryGracePeriodSeconds *int64  `json:"retryGracePeriodSeconds,omitempty"`
}

// One custom scope associated with a user pool resource server. This data type
// is a member of ResourceServerScopeType. For more information, see Scopes,
// M2M, and API authorization with resource servers (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-define-resource-servers.html).
type ResourceServerScopeType struct {
	ScopeDescription *string `json:"scopeDescription,omitempty"`
	ScopeName        *string `json:"scopeName,omitempty"`
}

// The details of a resource server configuration and associated custom scopes
// in a user pool.
type ResourceServerType struct {
	Identifier *string                    `json:"identifier,omitempty"`
	Name       *string                    `json:"name,omitempty"`
	Scopes     []*ResourceServerScopeType `json:"scopes,omitempty"`
	UserPoolID *string                    `json:"userPoolID,omitempty"`
}

// The settings of risk configuration for threat protection with threat protection
// in a user pool.
type RiskConfigurationType struct {
	ClientID         *string      `json:"clientID,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	UserPoolID       *string      `json:"userPoolID,omitempty"`
}

// A user's preference for using SMS message multi-factor authentication (MFA).
// Turns SMS MFA on and off, and can set SMS as preferred when other MFA options
// are available. You can't turn off SMS MFA for any of your users when MFA
// is required in your user pool; you can only set the type that your user prefers.
type SMSMFASettingsType struct {
	Enabled      *bool `json:"enabled,omitempty"`
	PreferredMFA *bool `json:"preferredMFA,omitempty"`
}

// A list of the user attributes and their properties in your user pool. The
// attribute schema contains standard attributes, custom attributes with a custom:
// prefix, and developer attributes with a dev: prefix. For more information,
// see User pool attributes (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html).
//
// Developer-only dev: attributes are a legacy feature of user pools, and are
// read-only to all app clients. You can create and update developer-only attributes
// only with IAM-authenticated API operations. Use app client read/write permissions
// instead.
type SchemaAttributeType struct {
	AttributeDataType      *string `json:"attributeDataType,omitempty"`
	DeveloperOnlyAttribute *bool   `json:"developerOnlyAttribute,omitempty"`
	Mutable                *bool   `json:"mutable,omitempty"`
	Name                   *string `json:"name,omitempty"`
	// The minimum and maximum values of an attribute that is of the number type,
	// for example custom:age.
	NumberAttributeConstraints *NumberAttributeConstraintsType `json:"numberAttributeConstraints,omitempty"`
	Required                   *bool                           `json:"required,omitempty"`
	// The minimum and maximum length values of an attribute that is of the string
	// type, for example custom:department.
	StringAttributeConstraints *StringAttributeConstraintsType `json:"stringAttributeConstraints,omitempty"`
}

// User pool configuration for delivery of SMS messages with Amazon Simple Notification
// Service. To send SMS messages with Amazon SNS in the Amazon Web Services
// Region that you want, the Amazon Cognito user pool uses an Identity and Access
// Management (IAM) role in your Amazon Web Services account.
type SmsConfigurationType struct {
	// The configuration that Amazon Cognito uses to send SMS messages through Amazon
	// Web Services End User Messaging SMS. Provide this structure in the EumsSms
	// member of SmsConfigurationType to use Amazon Web Services End User Messaging
	// SMS instead of Amazon SNS.
	EumsSms      *EumsSmsConfigurationType `json:"eumsSms,omitempty"`
	ExternalID   *string                   `json:"externalID,omitempty"`
	SNSCallerARN *string                   `json:"snsCallerARN,omitempty"`
	SNSRegion    *string                   `json:"snsRegion,omitempty"`
}

// The configuration of multi-factor authentication (MFA) with SMS messages
// in a user pool.
type SmsMFAConfigType struct {
	SmsAuthenticationMessage *string `json:"smsAuthenticationMessage,omitempty"`
	// User pool configuration for delivery of SMS messages with Amazon Simple Notification
	// Service. To send SMS messages with Amazon SNS in the Amazon Web Services
	// Region that you want, the Amazon Cognito user pool uses an Identity and Access
	// Management (IAM) role in your Amazon Web Services account.
	SmsConfiguration *SmsConfigurationType `json:"smsConfiguration,omitempty"`
}

// Settings for time-based one-time password (TOTP) multi-factor authentication
// (MFA) in a user pool. Enables and disables availability of this feature.
type SoftwareTokenMFAConfigType struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// A user's preference for using time-based one-time password (TOTP) multi-factor
// authentication (MFA). Turns TOTP MFA on and off, and can set TOTP as preferred
// when other MFA options are available. You can't turn off TOTP MFA for any
// of your users when MFA is required in your user pool; you can only set the
// type that your user prefers.
type SoftwareTokenMFASettingsType struct {
	Enabled      *bool `json:"enabled,omitempty"`
	PreferredMFA *bool `json:"preferredMFA,omitempty"`
}

// The minimum and maximum length values of an attribute that is of the string
// type, for example custom:department.
type StringAttributeConstraintsType struct {
	MaxLength *string `json:"maxLength,omitempty"`
	MinLength *string `json:"minLength,omitempty"`
}

// The details of a set of terms documents. For more information, see Terms
// documents (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-managed-login.html#managed-login-terms-documents).
type TermsDescriptionType struct {
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
}

// The details of a set of terms documents. For more information, see Terms
// documents (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-managed-login.html#managed-login-terms-documents).
type TermsType struct {
	ClientID         *string      `json:"clientID,omitempty"`
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	UserPoolID       *string      `json:"userPoolID,omitempty"`
}

// The time units that, with IdTokenValidity, AccessTokenValidity, and RefreshTokenValidity,
// set and display the duration of ID, access, and refresh tokens for an app
// client. You can assign a separate token validity unit to each type of token.
type TokenValidityUnitsType struct {
	AccessToken  *string `json:"accessToken,omitempty"`
	IDToken      *string `json:"idToken,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
}

// A container for the UI customization information for the hosted UI in a user
// pool.
type UICustomizationType struct {
	ClientID         *string      `json:"clientID,omitempty"`
	CreationDate     *metav1.Time `json:"creationDate,omitempty"`
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	UserPoolID       *string      `json:"userPoolID,omitempty"`
}

// The settings for updates to user attributes. These settings include the property
// AttributesRequireVerificationBeforeUpdate,a user-pool setting that tells
// Amazon Cognito how to handle changes to the value of your users' email address
// and phone number attributes. Formore information, see Verifying updates to
// email addresses and phone numbers (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html#user-pool-settings-verifications-verify-attribute-updates).
type UserAttributeUpdateSettingsType struct {
	AttributesRequireVerificationBeforeUpdate []*string `json:"attributesRequireVerificationBeforeUpdate,omitempty"`
}

// Contextual data, such as the user's device fingerprint, IP address, or location,
// used for evaluating the risk of an unexpected event by Amazon Cognito threat
// protection.
type UserContextDataType struct {
	EncodedData *string `json:"encodedData,omitempty"`
	IPAddress   *string `json:"ipAddress,omitempty"`
}

// A user import job in a user pool. Describes the status of user import with
// a CSV file. For more information, see Importing users into user pools from
// a CSV file (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-using-import-tool.html).
type UserImportJobType struct {
	CloudWatchLogsRoleARN *string      `json:"cloudWatchLogsRoleARN,omitempty"`
	CompletionDate        *metav1.Time `json:"completionDate,omitempty"`
	CreationDate          *metav1.Time `json:"creationDate,omitempty"`
	StartDate             *metav1.Time `json:"startDate,omitempty"`
	UserPoolID            *string      `json:"userPoolID,omitempty"`
}

// Contains settings for activation of threat protection, including the operating
// mode and additional authentication types. To log user security information
// but take no action, set to AUDIT. To configure automatic security responses
// to potentially unwanted traffic to your user pool, set to ENFORCED.
//
// For more information, see Adding advanced security to a user pool (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security.html).
// To activate this setting, your user pool must be on the Plus tier (https://docs.aws.amazon.com/cognito/latest/developerguide/feature-plans-features-plus.html).
type UserPoolAddOnsType struct {
	AdvancedSecurityMode *string `json:"advancedSecurityMode,omitempty"`
}

// A short description of a user pool app client.
type UserPoolClientDescription struct {
	ClientID   *string `json:"clientID,omitempty"`
	ClientName *string `json:"clientName,omitempty"`
	UserPoolID *string `json:"userPoolID,omitempty"`
}

// The configuration of a user pool client.
type UserPoolClientType struct {
	AccessTokenValidity             *int64    `json:"accessTokenValidity,omitempty"`
	AllowedOAuthFlows               []*string `json:"allowedOAuthFlows,omitempty"`
	AllowedOAuthFlowsUserPoolClient *bool     `json:"allowedOAuthFlowsUserPoolClient,omitempty"`
	AllowedOAuthScopes              []*string `json:"allowedOAuthScopes,omitempty"`
	// The settings for Amazon Pinpoint analytics configuration. With an analytics
	// configuration, your application can collect user-activity metrics for user
	// notifications with a Amazon Pinpoint campaign.
	//
	// Amazon Pinpoint isn't available in all Amazon Web Services Regions. For a
	// list of available Regions, see Amazon Cognito and Amazon Pinpoint Region
	// availability (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html#cognito-user-pools-find-region-mappings).
	AnalyticsConfiguration                   *AnalyticsConfigurationType `json:"analyticsConfiguration,omitempty"`
	AuthSessionValidity                      *int64                      `json:"authSessionValidity,omitempty"`
	CallbackURLs                             []*string                   `json:"callbackURLs,omitempty"`
	ClientID                                 *string                     `json:"clientID,omitempty"`
	ClientName                               *string                     `json:"clientName,omitempty"`
	CreationDate                             *metav1.Time                `json:"creationDate,omitempty"`
	DefaultRedirectURI                       *string                     `json:"defaultRedirectURI,omitempty"`
	EnablePropagateAdditionalUserContextData *bool                       `json:"enablePropagateAdditionalUserContextData,omitempty"`
	EnableTokenRevocation                    *bool                       `json:"enableTokenRevocation,omitempty"`
	ExplicitAuthFlows                        []*string                   `json:"explicitAuthFlows,omitempty"`
	IDTokenValidity                          *int64                      `json:"idTokenValidity,omitempty"`
	LastModifiedDate                         *metav1.Time                `json:"lastModifiedDate,omitempty"`
	LogoutURLs                               []*string                   `json:"logoutURLs,omitempty"`
	PreventUserExistenceErrors               *string                     `json:"preventUserExistenceErrors,omitempty"`
	ReadAttributes                           []*string                   `json:"readAttributes,omitempty"`
	// The configuration of your app client for refresh token rotation. When enabled,
	// your app client issues new ID, access, and refresh tokens when users renew
	// their sessions with refresh tokens. When disabled, token refresh issues only
	// ID and access tokens.
	RefreshTokenRotation       *RefreshTokenRotationType `json:"refreshTokenRotation,omitempty"`
	RefreshTokenValidity       *int64                    `json:"refreshTokenValidity,omitempty"`
	SupportedIdentityProviders []*string                 `json:"supportedIdentityProviders,omitempty"`
	// The time units that, with IdTokenValidity, AccessTokenValidity, and RefreshTokenValidity,
	// set and display the duration of ID, access, and refresh tokens for an app
	// client. You can assign a separate token validity unit to each type of token.
	TokenValidityUnits *TokenValidityUnitsType `json:"tokenValidityUnits,omitempty"`
	UserPoolID         *string                 `json:"userPoolID,omitempty"`
	WriteAttributes    []*string               `json:"writeAttributes,omitempty"`
}

// A short description of a user pool.
type UserPoolDescriptionType struct {
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	ID           *string      `json:"id,omitempty"`
	// A collection of user pool Lambda triggers. Amazon Cognito invokes triggers
	// at several possible stages of user pool operations. Triggers can modify the
	// outcome of the operations that invoked them.
	LambdaConfig     *LambdaConfigType `json:"lambdaConfig,omitempty"`
	LastModifiedDate *metav1.Time      `json:"lastModifiedDate,omitempty"`
	Name             *string           `json:"name,omitempty"`
	ReplicaRegions   []*string         `json:"replicaRegions,omitempty"`
	Status           *string           `json:"status,omitempty"`
}

// A list of user pool policies. Contains the policy that sets password-complexity
// requirements.
type UserPoolPolicyType struct {
	// The password policy settings for a user pool, including complexity, history,
	// and length requirements.
	PasswordPolicy *PasswordPolicyType `json:"passwordPolicy,omitempty"`
}

// Contains information about a replica user pool, including Region, status,
// role, and ARN.
type UserPoolReplicaType struct {
	UserPoolARN *string `json:"userPoolARN,omitempty"`
}

// The configuration of a user pool.
type UserPoolType struct {
	// The settings for user message delivery in forgot-password operations. Contains
	// preference for email or SMS message delivery of password reset codes, or
	// for admin-only password reset.
	AccountRecoverySetting *AccountRecoverySettingType `json:"accountRecoverySetting,omitempty"`
	// The settings for administrator creation of users in a user pool. Contains
	// settings for allowing user sign-up, customizing invitation messages to new
	// users, and the amount of time before temporary passwords expire.
	AdminCreateUserConfig  *AdminCreateUserConfigType `json:"adminCreateUserConfig,omitempty"`
	AliasAttributes        []*string                  `json:"aliasAttributes,omitempty"`
	ARN                    *string                    `json:"arn,omitempty"`
	AutoVerifiedAttributes []*string                  `json:"autoVerifiedAttributes,omitempty"`
	CreationDate           *metav1.Time               `json:"creationDate,omitempty"`
	CustomDomain           *string                    `json:"customDomain,omitempty"`
	DeletionProtection     *string                    `json:"deletionProtection,omitempty"`
	// The device-remembering configuration for a user pool.
	//
	// When you provide a value for any property of DeviceConfiguration, you activate
	// the device remembering for the user pool.
	DeviceConfiguration *DeviceConfigurationType `json:"deviceConfiguration,omitempty"`
	Domain              *string                  `json:"domain,omitempty"`
	// The email configuration of your user pool. The email configuration type sets
	// your preferred sending method, Amazon Web Services Region, and sender for
	// messages from your user pool.
	//
	// Amazon Cognito can send email messages with Amazon Simple Email Service resources
	// in the Amazon Web Services Region where you created your user pool, and in
	// alternate Regions in some cases. For more information on the supported Regions,
	// see Email settings for Amazon Cognito user pools (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html).
	EmailConfiguration        *EmailConfigurationType `json:"emailConfiguration,omitempty"`
	EmailConfigurationFailure *string                 `json:"emailConfigurationFailure,omitempty"`
	EmailVerificationMessage  *string                 `json:"emailVerificationMessage,omitempty"`
	EmailVerificationSubject  *string                 `json:"emailVerificationSubject,omitempty"`
	EstimatedNumberOfUsers    *int64                  `json:"estimatedNumberOfUsers,omitempty"`
	ID                        *string                 `json:"id,omitempty"`
	// Specifies the issuer configuration for a user pool. Contains settings that
	// determine how tokens are issued and validated.
	IssuerConfiguration *IssuerConfigurationType `json:"issuerConfiguration,omitempty"`
	// Specifies the key configuration for a user pool. Contains settings for encryption
	// keys used to secure user pool data.
	KeyConfiguration *KeyConfigurationType `json:"keyConfiguration,omitempty"`
	// A collection of user pool Lambda triggers. Amazon Cognito invokes triggers
	// at several possible stages of user pool operations. Triggers can modify the
	// outcome of the operations that invoked them.
	LambdaConfig     *LambdaConfigType `json:"lambdaConfig,omitempty"`
	LastModifiedDate *metav1.Time      `json:"lastModifiedDate,omitempty"`
	MFAConfiguration *string           `json:"mfaConfiguration,omitempty"`
	Name             *string           `json:"name,omitempty"`
	// A list of user pool policies. Contains the policy that sets password-complexity
	// requirements.
	Policies                 *UserPoolPolicyType    `json:"policies,omitempty"`
	SchemaAttributes         []*SchemaAttributeType `json:"schemaAttributes,omitempty"`
	SmsAuthenticationMessage *string                `json:"smsAuthenticationMessage,omitempty"`
	// User pool configuration for delivery of SMS messages with Amazon Simple Notification
	// Service. To send SMS messages with Amazon SNS in the Amazon Web Services
	// Region that you want, the Amazon Cognito user pool uses an Identity and Access
	// Management (IAM) role in your Amazon Web Services account.
	SmsConfiguration        *SmsConfigurationType `json:"smsConfiguration,omitempty"`
	SmsConfigurationFailure *string               `json:"smsConfigurationFailure,omitempty"`
	SmsVerificationMessage  *string               `json:"smsVerificationMessage,omitempty"`
	Status                  *string               `json:"status,omitempty"`
	// The settings for updates to user attributes. These settings include the property
	// AttributesRequireVerificationBeforeUpdate,a user-pool setting that tells
	// Amazon Cognito how to handle changes to the value of your users' email address
	// and phone number attributes. Formore information, see Verifying updates to
	// email addresses and phone numbers (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html#user-pool-settings-verifications-verify-attribute-updates).
	UserAttributeUpdateSettings *UserAttributeUpdateSettingsType `json:"userAttributeUpdateSettings,omitempty"`
	// Contains settings for activation of threat protection, including the operating
	// mode and additional authentication types. To log user security information
	// but take no action, set to AUDIT. To configure automatic security responses
	// to potentially unwanted traffic to your user pool, set to ENFORCED.
	//
	// For more information, see Adding advanced security to a user pool (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security.html).
	// To activate this setting, your user pool must be on the Plus tier (https://docs.aws.amazon.com/cognito/latest/developerguide/feature-plans-features-plus.html).
	UserPoolAddOns     *UserPoolAddOnsType `json:"userPoolAddOns,omitempty"`
	UserPoolTags       map[string]*string  `json:"userPoolTags,omitempty"`
	UsernameAttributes []*string           `json:"usernameAttributes,omitempty"`
	// The configuration of a user pool for username case sensitivity.
	UsernameConfiguration *UsernameConfigurationType `json:"usernameConfiguration,omitempty"`
	// The template for the verification message that your user pool delivers to
	// users who set an email address or phone number attribute.
	VerificationMessageTemplate *VerificationMessageTemplateType `json:"verificationMessageTemplate,omitempty"`
}

// A user profile in a Amazon Cognito user pool.
type UserType struct {
	Enabled              *bool        `json:"enabled,omitempty"`
	UserCreateDate       *metav1.Time `json:"userCreateDate,omitempty"`
	UserLastModifiedDate *metav1.Time `json:"userLastModifiedDate,omitempty"`
}

// The configuration of a user pool for username case sensitivity.
type UsernameConfigurationType struct {
	CaseSensitive *bool `json:"caseSensitive,omitempty"`
}

// The template for the verification message that your user pool delivers to
// users who set an email address or phone number attribute.
type VerificationMessageTemplateType struct {
	DefaultEmailOption *string `json:"defaultEmailOption,omitempty"`
	EmailMessage       *string `json:"emailMessage,omitempty"`
	EmailMessageByLink *string `json:"emailMessageByLink,omitempty"`
	EmailSubject       *string `json:"emailSubject,omitempty"`
	EmailSubjectByLink *string `json:"emailSubjectByLink,omitempty"`
	SmsMessage         *string `json:"smsMessage,omitempty"`
}

// The details of a passkey, or webauthN, biometric or security-key authentication
// factor for a user.
type WebAuthnCredentialDescription struct {
	CreatedAt              *metav1.Time `json:"createdAt,omitempty"`
	CredentialID           *string      `json:"credentialID,omitempty"`
	FriendlyCredentialName *string      `json:"friendlyCredentialName,omitempty"`
	RelyingPartyID         *string      `json:"relyingPartyID,omitempty"`
}

// A user's preference for using passkey, or WebAuthn, multi-factor authentication
// (MFA). Turns passkey MFA on and off for the user. Unlike other MFA settings
// types, this type doesn't include a PreferredMfa option because passkey MFA
// applies only when passkey is the first authentication factor.
type WebAuthnMFASettingsType struct {
	Enabled *bool `json:"enabled,omitempty"`
}
