// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UserPoolClientSecretSpec defines the desired state of UserPoolClientSecret.
type UserPoolClientSecretSpec struct {

	// The client secret value you want to use. If you don't provide this parameter,
	// Amazon Cognito generates a secure secret for you.
	//
	// Regex Pattern: `^[\w+]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ClientSecret *ackv1alpha1.SecretKeyReference `json:"clientSecret,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ExportTo *ackv1alpha1.SecretKeyReference `json:"exportTo,omitempty"`
	// The ID of the app client for which you want to create a new secret.
	//
	// Regex Pattern: `^[\w+]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	UserPoolClientID  *string                                  `json:"userPoolClientId,omitempty"`
	UserPoolClientRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"userPoolClientRef,omitempty"`
	// The ID of the user pool that contains the app client.
	//
	// Regex Pattern: `^[\w-]+_[0-9a-zA-Z]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	UserPoolID  *string                                  `json:"userPoolId,omitempty"`
	UserPoolRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"userPoolRef,omitempty"`
}

// UserPoolClientSecretStatus defines the observed state of UserPoolClientSecret
type UserPoolClientSecretStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time when the client secret was created.
	// +kubebuilder:validation:Optional
	ClientSecretCreateDate *metav1.Time `json:"clientSecretCreateDate,omitempty"`
	// The unique identifier for the client secret. This identifier follows the
	// format --.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
}

// UserPoolClientSecret is the Schema for the UserPoolClientSecrets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type UserPoolClientSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserPoolClientSecretSpec   `json:"spec,omitempty"`
	Status            UserPoolClientSecretStatus `json:"status,omitempty"`
}

// UserPoolClientSecretList contains a list of UserPoolClientSecret
// +kubebuilder:object:root=true
type UserPoolClientSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserPoolClientSecret `json:"items"`
}

func init() {
	SchemeBuilder.Register(&UserPoolClientSecret{}, &UserPoolClientSecretList{})
}
