// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UserPoolSpec defines the desired state of UserPool.
type UserPoolSpec struct {

	// The available verified method a user can use to recover their password when
	// they call ForgotPassword. You can use this setting to define a preferred
	// method when a user has more than one method available. With this setting,
	// SMS doesn't qualify for a valid password recovery mechanism if the user also
	// has SMS multi-factor authentication (MFA) activated. Email MFA is also disqualifying
	// for account recovery with email. In the absence of this setting, Amazon Cognito
	// uses the legacy behavior to determine the recovery method where SMS is preferred
	// over email.
	//
	// As a best practice, configure both verified_email and verified_phone_number,
	// with one having a higher priority than the other.
	AccountRecoverySetting *AccountRecoverySettingType `json:"accountRecoverySetting,omitempty"`
	// The configuration for administrative creation of users. Includes the template
	// for the invitation message for new users, the duration of temporary passwords,
	// and permitting self-service sign-up.
	AdminCreateUserConfig *AdminCreateUserConfigType `json:"adminCreateUserConfig,omitempty"`
	// Attributes supported as an alias for this user pool. For more information
	// about alias attributes, see Customizing sign-in attributes (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases).
	AliasAttributes []*string `json:"aliasAttributes,omitempty"`
	// The attributes that you want your user pool to automatically verify. For
	// more information, see Verifying contact information at sign-up (https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html#allowing-users-to-sign-up-and-confirm-themselves).
	AutoVerifiedAttributes []*string `json:"autoVerifiedAttributes,omitempty"`
	// When active, DeletionProtection prevents accidental deletion of your userpool.
	// Before you can delete a user pool that you have protected against deletion,
	// youmust deactivate this feature.
	//
	// When you try to delete a protected user pool in a DeleteUserPool API request,
	// Amazon Cognito returns an InvalidParameterException error. To delete a protected
	// user pool, send a new DeleteUserPool request after you deactivate deletion
	// protection in an UpdateUserPool API request.
	DeletionProtection *string `json:"deletionProtection,omitempty"`
	// The device-remembering configuration for a user pool. Device remembering
	// or device tracking is a "Remember me on this device" option for user pools
	// that perform authentication with the device key of a trusted device in the
	// back end, instead of a user-provided MFA code. For more information about
	// device authentication, see Working with user devices in your user pool (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html).
	// A null value indicates that you have deactivated device remembering in your
	// user pool.
	//
	// When you provide a value for any DeviceConfiguration field, you activate
	// the Amazon Cognito device-remembering feature. For more information, see
	// Working with devices (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html).
	DeviceConfiguration *DeviceConfigurationType `json:"deviceConfiguration,omitempty"`
	// The email configuration of your user pool. The email configuration type sets
	// your preferred sending method, Amazon Web Services Region, and sender for
	// messages from your user pool.
	EmailConfiguration *EmailConfigurationType `json:"emailConfiguration,omitempty"`
	// This parameter is no longer used.
	//
	// Regex Pattern: `^[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*$`
	EmailVerificationMessage *string `json:"emailVerificationMessage,omitempty"`
	// This parameter is no longer used.
	//
	// Regex Pattern: `^[\p{L}\p{M}\p{S}\p{N}\p{P}\s]+$`
	EmailVerificationSubject *string `json:"emailVerificationSubject,omitempty"`
	// The issuer configuration for the user pool. Specifies the issuer type for
	// token generation.
	IssuerConfiguration *IssuerConfigurationType `json:"issuerConfiguration,omitempty"`
	// The key configuration for the user pool. Specifies the key type and KMS key
	// ARN for encryption.
	KeyConfiguration *KeyConfigurationType `json:"keyConfiguration,omitempty"`
	// A collection of user pool Lambda triggers. Amazon Cognito invokes triggers
	// at several possible stages of authentication operations. Triggers can modify
	// the outcome of the operations that invoked them.
	LambdaConfig *LambdaConfigType `json:"lambdaConfig,omitempty"`
	// Sets multi-factor authentication (MFA) to be on, off, or optional. When ON,
	// all users must set up MFA before they can sign in. When OPTIONAL, your application
	// must make a client-side determination of whether a user wants to register
	// an MFA device. For user pools with adaptive authentication with threat protection,
	// choose OPTIONAL.
	//
	// When MfaConfiguration is OPTIONAL, managed login doesn't automatically prompt
	// users to set up MFA. Amazon Cognito generates MFA prompts in API responses
	// and in managed login for users who have chosen and configured a preferred
	// MFA factor.
	//
	// The CreateUserPool operation supports only SMS MFA configuration. If you
	// set MfaConfiguration to either of these values, include an SmsConfiguration
	// in the same request:
	//
	//   - ON – Requires MFA for all users
	//
	//   - OPTIONAL – Makes MFA optional for each user
	//
	// If you omit SmsConfiguration, the operation returns an InvalidParameterException.
	// To configure TOTP or email MFA, use the SetUserPoolMfaConfig (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserPoolMfaConfig.html)
	// operation. You can also use SetUserPoolMfaConfig to add MFA factors later.
	MFAConfiguration *string `json:"mfaConfiguration,omitempty"`
	// A friendly name for your user pool.
	//
	// Regex Pattern: `^[\w\s+=,.@-]+$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The password policy and sign-in policy in the user pool. The password policy
	// sets options like password complexity requirements and password history.
	// The sign-in policy sets the options available to applications in choice-based
	// authentication (https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flows-selection-sdk.html#authentication-flows-selection-choice).
	Policies *UserPoolPolicyType `json:"policies,omitempty"`
	// An array of attributes for the new user pool. You can add custom attributes
	// and modify the properties of default attributes. The specifications in this
	// parameter set the required attributes in your user pool. For more information,
	// see Working with user attributes (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html).
	Schema []*SchemaAttributeType `json:"schema,omitempty"`
	// The contents of the SMS message that your user pool sends to users in SMS
	// OTP and MFA authentication.
	//
	// Regex Pattern: `\{####\}`
	SmsAuthenticationMessage *string `json:"smsAuthenticationMessage,omitempty"`
	// The settings for your Amazon Cognito user pool to send SMS messages with
	// Amazon Simple Notification Service. To send SMS messages with Amazon SNS
	// in the Amazon Web Services Region that you want, the Amazon Cognito user
	// pool uses an Identity and Access Management (IAM) role in your Amazon Web
	// Services account. For more information see SMS message settings (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-sms-settings.html).
	SmsConfiguration *SmsConfigurationType `json:"smsConfiguration,omitempty"`
	// This parameter is no longer used.
	//
	// Regex Pattern: `\{####\}`
	SmsVerificationMessage *string `json:"smsVerificationMessage,omitempty"`
	// An array of tag keys and values that you want to assign to the user pool.
	Tags map[string]*string `json:"tags,omitempty"`
	// The settings for updates to user attributes. These settings include the property
	// AttributesRequireVerificationBeforeUpdate,a user-pool setting that tells
	// Amazon Cognito how to handle changes to the value of your users' email address
	// and phone number attributes. Formore information, see Verifying updates to
	// email addresses and phone numbers (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html#user-pool-settings-verifications-verify-attribute-updates).
	UserAttributeUpdateSettings *UserAttributeUpdateSettingsType `json:"userAttributeUpdateSettings,omitempty"`
	// Contains settings for activation of threat protection, including the operating
	// mode and additional authentication types. To log user security information
	// but take no action, set to AUDIT. To configure automatic security responses
	// to potentially unwanted traffic to your user pool, set to ENFORCED.
	//
	// For more information, see Adding advanced security to a user pool (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-advanced-security.html).
	// To activate this setting, your user pool must be on the Plus tier (https://docs.aws.amazon.com/cognito/latest/developerguide/feature-plans-features-plus.html).
	UserPoolAddOns *UserPoolAddOnsType `json:"userPoolAddOns,omitempty"`
	// The tag keys and values to assign to the user pool. A tag is a label that
	// you can use to categorize and manage user pools in different ways, such as
	// by purpose, owner, environment, or other criteria.
	UserPoolTags map[string]*string `json:"userPoolTags,omitempty"`
	// Specifies whether a user can use an email address or phone number as a username
	// when they sign up. For more information, see Customizing sign-in attributes
	// (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases).
	UsernameAttributes []*string `json:"usernameAttributes,omitempty"`
	// Sets the case sensitivity option for sign-in usernames. When CaseSensitive
	// is false (case insensitive), users can sign in with any combination of capital
	// and lowercase letters. For example, username, USERNAME, or UserName, or for
	// email, email@example.com or EMaiL@eXamplE.Com. For most use cases, set case
	// sensitivity to false as a best practice. When usernames and email addresses
	// are case insensitive, Amazon Cognito treats any variation in case as the
	// same user, and prevents a case variation from being assigned to the same
	// attribute for a different user.
	//
	// When CaseSensitive is true (case sensitive), Amazon Cognito interprets USERNAME
	// and UserName as distinct users.
	//
	// This configuration is immutable after you set it.
	UsernameConfiguration *UsernameConfigurationType `json:"usernameConfiguration,omitempty"`
	// The template for the verification message that your user pool delivers to
	// users who set an email address or phone number attribute.
	//
	// Set the email message type that corresponds to your DefaultEmailOption selection.
	// For CONFIRM_WITH_LINK, specify an EmailMessageByLink and leave EmailMessage
	// blank. For CONFIRM_WITH_CODE, specify an EmailMessage and leave EmailMessageByLink
	// blank. When you supply both parameters with either choice, Amazon Cognito
	// returns an error.
	VerificationMessageTemplate *VerificationMessageTemplateType `json:"verificationMessageTemplate,omitempty"`
}

// UserPoolStatus defines the observed state of UserPool
type UserPoolStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time when the item was created. Amazon Cognito returns this
	// timestamp in UNIX epoch time format. Your SDK might render the output in
	// a human-readable format like ISO 8601 or a Java Date object.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// A custom domain name that you provide to Amazon Cognito. This parameter applies
	// only if you use a custom domain to host the sign-up and sign-in pages for
	// your application. An example of a custom domain name might be auth.example.com.
	//
	// For more information about adding a custom domain to your user pool, see
	// Using Your Own Domain for the Hosted UI (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html).
	//
	// Regex Pattern: `^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$`
	// +kubebuilder:validation:Optional
	CustomDomain *string `json:"customDomain,omitempty"`
	// The domain prefix, if the user pool has a domain associated with it.
	//
	// Regex Pattern: `^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$`
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty"`
	// Deprecated. Review error codes from API requests with EventSource:cognito-idp.amazonaws.com
	// in CloudTrail for information about problems with user pool email configuration.
	// +kubebuilder:validation:Optional
	EmailConfigurationFailure *string `json:"emailConfigurationFailure,omitempty"`
	// A number estimating the size of the user pool.
	// +kubebuilder:validation:Optional
	EstimatedNumberOfUsers *int64 `json:"estimatedNumberOfUsers,omitempty"`
	// The ID of the user pool.
	//
	// Regex Pattern: `^[\w-]+_[0-9a-zA-Z]+$`
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The date and time when the item was modified. Amazon Cognito returns this
	// timestamp in UNIX epoch time format. Your SDK might render the output in
	// a human-readable format like ISO 8601 or a Java Date object.
	// +kubebuilder:validation:Optional
	LastModifiedDate *metav1.Time `json:"lastModifiedDate,omitempty"`
	// A list of the user attributes and their properties in your user pool. The
	// attribute schema contains standard attributes, custom attributes with a custom:
	// prefix, and developer attributes with a dev: prefix. For more information,
	// see User pool attributes (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html).
	//
	// Developer-only attributes are a legacy feature of user pools, and are read-only
	// to all app clients. You can create and update developer-only attributes only
	// with IAM-authenticated API operations. Use app client read/write permissions
	// instead.
	// +kubebuilder:validation:Optional
	SchemaAttributes []*SchemaAttributeType `json:"schemaAttributes,omitempty"`
	// The reason why the SMS configuration can't send the messages to your users.
	//
	// This message might include comma-separated values to describe why your SMS
	// configuration can't send messages to user pool end users.
	//
	// InvalidSmsRoleAccessPolicyException
	//
	// The Identity and Access Management role that Amazon Cognito uses to send
	// SMS messages isn't properly configured. For more information, see SmsConfigurationType
	// (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SmsConfigurationType.html).
	//
	// SNSSandbox
	//
	// The Amazon Web Services account is in the SNS SMS Sandbox and messages will
	// only reach verified end users. This parameter won’t get populated with
	// SNSSandbox if the user creating the user pool doesn’t have SNS permissions.
	// To learn how to move your Amazon Web Services account out of the sandbox,
	// see Moving out of the SMS sandbox (https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox-moving-to-production.html).
	// +kubebuilder:validation:Optional
	SmsConfigurationFailure *string `json:"smsConfigurationFailure,omitempty"`
	// This parameter is no longer used.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// UserPool is the Schema for the UserPools API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type UserPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserPoolSpec   `json:"spec,omitempty"`
	Status            UserPoolStatus `json:"status,omitempty"`
}

// UserPoolList contains a list of UserPool
// +kubebuilder:object:root=true
type UserPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserPool `json:"items"`
}

func init() {
	SchemeBuilder.Register(&UserPool{}, &UserPoolList{})
}
