// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package user_pool_client_secret

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.UserPoolClientID, b.ko.Spec.UserPoolClientID) {
		delta.Add("Spec.UserPoolClientID", a.ko.Spec.UserPoolClientID, b.ko.Spec.UserPoolClientID)
	} else if a.ko.Spec.UserPoolClientID != nil && b.ko.Spec.UserPoolClientID != nil {
		if *a.ko.Spec.UserPoolClientID != *b.ko.Spec.UserPoolClientID {
			delta.Add("Spec.UserPoolClientID", a.ko.Spec.UserPoolClientID, b.ko.Spec.UserPoolClientID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.UserPoolClientRef, b.ko.Spec.UserPoolClientRef) {
		delta.Add("Spec.UserPoolClientRef", a.ko.Spec.UserPoolClientRef, b.ko.Spec.UserPoolClientRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID) {
		delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
	} else if a.ko.Spec.UserPoolID != nil && b.ko.Spec.UserPoolID != nil {
		if *a.ko.Spec.UserPoolID != *b.ko.Spec.UserPoolID {
			delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef) {
		delta.Add("Spec.UserPoolRef", a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef)
	}

	return delta
}
