// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package user_pool_client_secret

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/cognitoidentityprovider-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.UserPoolClientSecret{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	return rm.customFind(ctx, r)
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	if desired.ko.Spec.ClientSecret != nil && desired.ko.Spec.ExportTo != nil {
		return nil, ackerr.NewTerminalError(fmt.Errorf("only one of spec.clientSecret or spec.exportTo may be specified"))
	}
	if desired.ko.Spec.ClientSecret == nil && desired.ko.Spec.ExportTo == nil {
		return nil, ackerr.NewTerminalError(fmt.Errorf("one of spec.clientSecret or spec.exportTo must be specified"))
	}
	if desired.ko.Spec.ExportTo != nil {
		if err := rm.validateExportTarget(ctx, desired.ko); err != nil {
			return nil, err
		}
	}

	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	if desired.ko.Spec.ClientSecret != nil && input.ClientSecret == nil {
		return nil, ackerr.NewTerminalError(fmt.Errorf("spec.clientSecret must reference a non-empty Secret value"))
	}

	var resp *svcsdk.AddUserPoolClientSecretOutput
	_ = resp
	resp, err = rm.sdkapi.AddUserPoolClientSecret(ctx, input)
	if err == nil && resp.ClientSecretDescriptor == nil {
		return nil, ackerr.NewTerminalError(fmt.Errorf("Cognito did not return a client secret descriptor"))
	}

	rm.metrics.RecordAPICall("CREATE", "AddUserPoolClientSecret", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ClientSecretDescriptor.ClientSecretCreateDate != nil {
		ko.Status.ClientSecretCreateDate = &metav1.Time{*resp.ClientSecretDescriptor.ClientSecretCreateDate}
	} else {
		ko.Status.ClientSecretCreateDate = nil
	}
	if resp.ClientSecretDescriptor.ClientSecretId != nil {
		ko.Status.ID = resp.ClientSecretDescriptor.ClientSecretId
	} else {
		ko.Status.ID = nil
	}

	rm.setStatusDefaults(ko)
	if desired.ko.Spec.ExportTo != nil {
		if resp.ClientSecretDescriptor.ClientSecretValue == nil {
			return &resource{ko}, ackerr.NewTerminalError(fmt.Errorf("Cognito did not return a generated client secret"))
		}
		if err = rm.exportGeneratedSecret(ctx, desired.ko, *resp.ClientSecretDescriptor.ClientSecretValue); err != nil {
			return &resource{ko}, err
		}
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.AddUserPoolClientSecretInput, error) {
	res := &svcsdk.AddUserPoolClientSecretInput{}

	if r.ko.Spec.UserPoolClientID != nil {
		res.ClientId = r.ko.Spec.UserPoolClientID
	}
	if r.ko.Spec.ClientSecret != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.ClientSecret)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.ClientSecret = aws.String(tmpSecret)
		}
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteUserPoolClientSecretOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteUserPoolClientSecret(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteUserPoolClientSecret", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteUserPoolClientSecretInput, error) {
	res := &svcsdk.DeleteUserPoolClientSecretInput{}

	if r.ko.Spec.UserPoolClientID != nil {
		res.ClientId = r.ko.Spec.UserPoolClientID
	}
	if r.ko.Status.ID != nil {
		res.ClientSecretId = r.ko.Status.ID
	}
	if r.ko.Spec.UserPoolID != nil {
		res.UserPoolId = r.ko.Spec.UserPoolID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.UserPoolClientSecret,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterException":
		return true
	default:
		return false
	}
}
func (rm *resourceManager) customFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	if r.ko.Spec.UserPoolID == nil || r.ko.Spec.UserPoolClientID == nil || r.ko.Status.ID == nil {
		return nil, ackerr.NotFound
	}

	resp, err := rm.sdkapi.ListUserPoolClientSecrets(ctx, &svcsdk.ListUserPoolClientSecretsInput{
		ClientId:   r.ko.Spec.UserPoolClientID,
		UserPoolId: r.ko.Spec.UserPoolID,
	})
	rm.metrics.RecordAPICall("READ_ONE", "ListUserPoolClientSecrets", err)
	if err != nil {
		return nil, err
	}

	for _, descriptor := range resp.ClientSecrets {
		if descriptor.ClientSecretId == nil || *descriptor.ClientSecretId != *r.ko.Status.ID {
			continue
		}
		ko := r.ko.DeepCopy()
		if descriptor.ClientSecretCreateDate != nil {
			ko.Status.ClientSecretCreateDate = &metav1.Time{Time: *descriptor.ClientSecretCreateDate}
		}
		rm.setStatusDefaults(ko)
		return &resource{ko}, nil
	}

	return nil, ackerr.NotFound
}

func (rm *resourceManager) exportGeneratedSecret(
	ctx context.Context,
	ko *svcapitypes.UserPoolClientSecret,
	value string,
) error {
	ref := ko.Spec.ExportTo
	namespace := ref.Namespace
	if namespace == "" {
		namespace = ko.Namespace
	}
	return rm.rr.WriteToSecret(ctx, value, namespace, ref.Name, ref.Key)
}

func (rm *resourceManager) validateExportTarget(
	ctx context.Context,
	ko *svcapitypes.UserPoolClientSecret,
) error {
	ref := ko.Spec.ExportTo
	existing, err := rm.rr.SecretValueFromReference(ctx, ref)
	if err == nil && existing != "" {
		return ackerr.NewTerminalError(fmt.Errorf("target Secret %q key %q already contains a value", ref.Name, ref.Key))
	}
	if err != nil && !errors.Is(err, ackerr.SecretNotFound) {
		return err
	}
	if errors.Is(err, ackerr.SecretNotFound) {
		// WriteToSecret cannot distinguish a missing key from a missing Secret.
		// It will perform the definitive existence check before writing.
		return nil
	}
	return nil
}
